"use strict";
const { requireFromSidekick } = require("./lib/deps");
const { z } = requireFromSidekick("zod");
const profiles = require("./lib/profiles");
const { createClient } = require("./lib/client");
const providers = require("./lib/providers");
const { NetworkFirewallError } = require("./lib/errors");
const v = require("./lib/validate");

function result(payload) { return { content:[{type:"text", text:JSON.stringify(payload,null,2)}]}; }
function errorResult(error) { const code=error?.code || "internal_error"; return {content:[{type:"text",text:JSON.stringify({ok:false,code,error:String(error?.message || error).replace(/\s+/g," ").slice(0,500),details:error?.details || {}},null,2)}],isError:true,code}; }
function guard(fn) { return services => async (args,runtime) => { try { return result(await fn(services,args,runtime)); } catch(e) { return errorResult(e); } }; }
function open(services,args,runtime) { const profile=profiles.resolve(services.config || {},args.profile); if(!profile.credential) throw new NetworkFirewallError("authentication_failed",`Credential for profile ${profile.name} could not be resolved`); return {profile,client:createClient(profile,runtime?.signal)}; }
function listActions() { return ["list_profiles","system","interfaces","networks","vlans","routes","gateways","clients","health","capabilities","summary","path","diagnose"]; }
function firewallActions() { return ["zones","rules","rule","nat","port_forwards","evaluate","diff"]; }
function readAction(name) { return async (services,args,runtime) => { if(args.action === "list_profiles") return {profiles:profiles.list(services.config || {})}; const {profile,client}=open(services,args,runtime); if(["system","interfaces","networks","routes","clients","health","capabilities"].includes(args.action)) return {ok:true,profile:profile.name,provider:profile.provider,action:args.action,data:await providers.read(profile,client,args.action === "vlans" ? "networks" : args.action)}; if(args.action === "summary") { const keys=["system","interfaces","networks","routes","health"]; const data={}; for(const key of keys) { try { data[key]=await providers.read(profile,client,key); } catch(e) { data[key]={state:"unavailable",code:e.code}; } } return {ok:true,profile:profile.name,provider:profile.provider,summary:data}; } if(args.action === "path" || args.action === "diagnose") return analyzePath(profile,args); throw new NetworkFirewallError("invalid_input",`Unknown ${name} action ${args.action}`); }; }
async function firewallRead(services,args,runtime) { const {profile,client}=open(services,args,runtime); if(args.action === "zones" || args.action === "rules" || args.action === "rule" || args.action === "nat" || args.action === "port_forwards") return {ok:true,profile:profile.name,provider:profile.provider,action:args.action,data:await providers.read(profile,client,"firewall")}; if(args.action === "evaluate") return analyzePath(profile,args); if(args.action === "diff") return {ok:true,profile:profile.name,state:"not_available",reason:"Provider-native configuration revision or effective-policy diff is not exposed by the selected adapter"}; throw new NetworkFirewallError("invalid_input",`Unknown firewall action ${args.action}`); }
async function dhcpRead(services,args,runtime) { const {profile,client}=open(services,args,runtime); return {ok:true,profile:profile.name,provider:profile.provider,action:args.action,data:await providers.read(profile,client,"dhcp")}; }
async function vpnRead(services,args,runtime) { const {profile,client}=open(services,args,runtime); return {ok:true,profile:profile.name,provider:profile.provider,action:args.action,data:await providers.read(profile,client,"vpn")}; }
function parseAddress(value,field) { if(typeof value !== "string") throw new NetworkFirewallError("invalid_input",`${field} is required`); return value.includes("/") ? v.cidr(value) : v.ip(value); }
function analyzePath(profile,args) { const source=parseAddress(args.source,"source"), destination=parseAddress(args.destination,"destination"); const protocol=String(args.protocol || "tcp").toLowerCase(); if(!["tcp","udp","icmp","icmpv6","sctp"].includes(protocol)) throw new NetworkFirewallError("invalid_input","protocol is unsupported"); if(["tcp","udp","sctp"].includes(protocol)) v.port(args.port,"port"); return {ok:true,profile:profile.name,provider:profile.provider,conclusion:"indeterminate",confidence:"low",source,destination,protocol,port:args.port || null,evidence:["A deterministic local analysis requires current provider route, interface, zone, and effective firewall state."],limitations:["No assertion of allow or deny is made without authoritative provider state and runtime-policy visibility."],source_state:"unknown",runtime_state:"unknown"}; }
function managementSafety(args) { const touched=String(args.change_type || args.action || ""); if(args.management_path_affected === true || args.management_path !== "safe") return {safe:false,risk:"critical",code:args.management_path === "affected" ? "management_path_affected" : "management_path_unknown",reason:"Sidekick cannot prove that this change preserves its authenticated management path"}; if(/default_route|management|vlan|route|vpn|firewall/i.test(touched) && args.management_path !== "safe") return {safe:false,risk:"critical",code:"management_path_unknown",reason:"Management-path analysis is required for this change"}; return {safe:true,risk:"high",reason:"Management-path analysis reports no impact; provider verification remains required"}; }
async function change(services,args,runtime) { const {profile,client}=open(services,args,runtime); const safety=managementSafety(args); const plan={profile:profile.name,provider:profile.provider,action:args.action,change_type:args.change_type || null,management_path:safety,revision:args.expected_revision || null,rollback:profile.provider === "openwrt" ? "provider_native_uci_timeout_and_confirm" : "not_established",proposed_change:{id:args.id || args.name || null,fields:Object.keys(args).filter(k=>!["profile","action","expected_revision","management_path","management_path_affected","change_type"].includes(k)).sort()}}; if(args.action === "plan" || args.action === "preflight") return {ok:true,state:"preflight_complete",safe_to_apply:safety.safe && profile.allow_mutations,plan}; if(!safety.safe) throw new NetworkFirewallError(safety.code,safety.reason,{plan}); if(args.action === "rollback") return {ok:false,state:"unsupported",reason:"No provider-native rollback target was established by this session"}; if(args.action === "apply") { if(!profile.allow_mutations) throw new NetworkFirewallError("mutation_disabled","Profile mutations are disabled",{plan}); if(profile.provider !== "openwrt") throw new NetworkFirewallError("unsupported_capability","This provider adapter does not yet expose a safe structured mutation with verified rollback semantics",{plan}); const applied=await providers.openwrtMutation(profile,client,args); return {ok:true,state:"applied",plan,evidence:applied}; } throw new NetworkFirewallError("invalid_input",`Unknown network_change action ${args.action}`); }
const entry={
  buildDescriptors() { return [
    {name:"network",aliases:["network_status"],description:"Bounded network discovery, health, capability negotiation, summaries, and deterministic connectivity analysis using an administrator-configured provider profile.",schema:z.object({action:z.enum(listActions()),profile:z.string().optional(),source:z.string().optional(),destination:z.string().optional(),protocol:z.string().optional(),port:z.number().int().min(1).max(65535).optional()}),args:{action:"string",profile:"string",source:"string",destination:"string",protocol:"string",port:"number"},risk:"low",category:"Infrastructure & Homelab",handler:guard(readAction("network"))},
    {name:"firewall",aliases:["firewall_status"],description:"Read configured firewall zones, rules, NAT where exposed, and bounded policy diagnostics. Configured and runtime state are labeled separately.",schema:z.object({action:z.enum(firewallActions()),profile:z.string().optional(),source:z.string().optional(),destination:z.string().optional(),protocol:z.string().optional(),port:z.number().int().min(1).max(65535).optional()}),args:{action:"string",profile:"string",source:"string",destination:"string",protocol:"string",port:"number"},risk:"low",category:"Infrastructure & Homelab",handler:guard(firewallRead)},
    {name:"dhcp",aliases:[],description:"Inspect provider-supported DHCP servers, scopes, leases, and reservations without treating missing data as healthy.",schema:z.object({action:z.enum(["status","leases","pools","reservations"]),profile:z.string().optional()}),args:{action:"string",profile:"string"},risk:"low",category:"Infrastructure & Homelab",handler:guard(dhcpRead)},
    {name:"vpn",aliases:[],description:"Inspect provider-supported VPN interfaces, tunnels, peers, handshakes, and statistics without returning private keys or shared secrets.",schema:z.object({action:z.enum(["status","interfaces","peers"]),profile:z.string().optional()}),args:{action:"string",profile:"string"},risk:"low",category:"Infrastructure & Homelab",handler:guard(vpnRead)},
    {name:"network_change",aliases:[],description:"Plan, preflight, and apply only structured provider changes after management-path safety analysis, policy, approval, provider-native protection, postcondition verification, and redacted evidence.",schema:z.object({action:z.enum(["plan","preflight","apply","rollback"]),profile:z.string().optional(),change_type:z.string().optional(),id:z.string().optional(),name:z.string().optional(),management_path:z.enum(["safe","affected","unknown"]).optional(),management_path_affected:z.boolean().optional(),expected_revision:z.string().optional(),dry_run:z.boolean().optional(),source:z.string().optional(),destination:z.string().optional(),protocol:z.string().optional(),port:z.number().int().min(1).max(65535).optional(),target:z.string().optional(),enabled:z.boolean().optional(),src:z.string().optional(),dest:z.string().optional(),src_ip:z.string().optional(),dest_ip:z.string().optional(),src_port:z.string().optional(),dest_port:z.string().optional(),family:z.string().optional(),description:z.string().max(200).optional()}),args:{action:"string",profile:"string",change_type:"string",id:"string",name:"string",management_path:"string",management_path_affected:"boolean",expected_revision:"string",dry_run:"boolean",target:"string",source:"string",destination:"string",protocol:"string",port:"number",enabled:"boolean"},risk:"critical",category:"Infrastructure & Homelab",handler:guard(change)},
  ]; },
  healthCheck({config}) { const profilesCount=Object.keys(config?.profiles || {}).length; return {ok:true,details:{state:profilesCount?"configured":"healthy-but-unconfigured",profiles:profilesCount,providers:["openwrt","opnsense","pfsense","unifi"],note:"Provider reachability and permissions require a selected profile health read."}}; },
};
module.exports={entry,buildDescriptors:entry.buildDescriptors,healthCheck:entry.healthCheck};
