"use strict";
const assert = require("assert");
const fs = require("fs");
const os = require("os");
const path = require("path");
const data = fs.mkdtempSync(path.join(os.tmpdir(), "sidekick-agent-receipts-"));
process.env.NODE_ENV = "test";
process.env.SIDEKICK_DATA_DIR = data;
process.env.SIDEKICK_SECRET_KEY_FILE = path.join(data, "secret");
fs.writeFileSync(process.env.SIDEKICK_SECRET_KEY_FILE, "test-only-key");
const { createTask } = require("../src/agent/task-model");
const tasks = require("../src/agent/task-store");
const receipts = require("../src/agent/receipt-store");
try {
  const task = createTask({ task_id: "agt_receipt01", objective: "receipt recovery", profile: "standard" });
  tasks.insertTask(task);
  const prepared = receipts.createReceipt({ task_id: task.task_id, action_fingerprint: "before-dispatch", capability: "write", args: { target: "workspace:test" }, idempotency_class: "idempotent", reversibility_class: "reversible" });
  assert.strictEqual(prepared.outcome_state, "pending");
  assert.strictEqual(receipts.evaluateRecovery({ receipt: prepared, postcondition: "unknown" }).decision, "escalate");
  const dispatched = receipts.createReceipt({ task_id: task.task_id, action_fingerprint: "during-dispatch", capability: "write", args: { target: "workspace:test" }, idempotency_class: "idempotent", reversibility_class: "reversible" });
  receipts.transitionReceipt(dispatched.receipt_id, "dispatched");
  assert.strictEqual(receipts.evaluateRecovery({ receipt: receipts.getReceipt(dispatched.receipt_id), postcondition: "absent", authorityAllowsRetry: true, policyAllowsRetry: true }).decision, "retry");
  receipts.transitionReceipt(dispatched.receipt_id, "ambiguous");
  assert.strictEqual(receipts.evaluateRecovery({ receipt: receipts.getReceipt(dispatched.receipt_id), postcondition: "absent", authorityAllowsRetry: true, policyAllowsRetry: true, targetState: "ambiguous" }).decision, "escalate");
  const approvalPending = receipts.createReceipt({ task_id: task.task_id, action_fingerprint: "approval-pending", capability: "write", args: {}, target_ref: "workspace:test", idempotency_class: "not_idempotent", reversibility_class: "irreversible" });
  receipts.transitionReceipt(approvalPending.receipt_id, "dispatched");
  receipts.transitionReceipt(approvalPending.receipt_id, "awaiting_approval");
  assert.strictEqual(receipts.getReceipt(approvalPending.receipt_id).outcome_state, "awaiting_approval");
  const finalized = receipts.createReceipt({ task_id: task.task_id, action_fingerprint: "after-effect", capability: "write", args: {}, target_ref: "workspace:test", idempotency_class: "not_idempotent", reversibility_class: "irreversible" });
  receipts.transitionReceipt(finalized.receipt_id, "dispatched");
  receipts.transitionReceipt(finalized.receipt_id, "finalized", { provider_receipt_ref: "provider-receipt" });
  assert.throws(() => receipts.transitionReceipt(finalized.receipt_id, "prepared"), /invalid receipt transition/);
  assert.strictEqual(receipts.evaluateRecovery({ receipt: receipts.getReceipt(finalized.receipt_id), postcondition: "unknown" }).decision, "completed");
  const retry = receipts.createRetryRecipe({ task_id: task.task_id, capability: "write", arguments: { target: "workspace:test", action: "create" }, target_ref: "workspace:test" });
  assert.ok(retry.recipe_id);
  assert.throws(() => receipts.createRetryRecipe({ task_id: task.task_id, capability: "write", arguments: { token: "secret" }, target_ref: "workspace:test" }), /safe|secret/);
  assert.throws(() => receipts.createRetryRecipe({ task_id: task.task_id, capability: "write", arguments: { target: "workspace:test" }, target_ref: "C:\\temp" }), /governed target/);
  assert.throws(() => receipts.createRecipe({ task_id: task.task_id, requirement_id: "oversized", check_type: "read", capability: "read", arguments: { value: "x".repeat(5000) } }), /oversized|string|too large/i);
  assert.throws(() => receipts.createReceipt({ task_id: task.task_id, action_fingerprint: "deep", capability: "write", args: {}, target_ref: "workspace:test", preconditions: Array.from({ length: 130 }, () => ({ ok: true })) }), /too many|too large/i);
  assert.throws(() => receipts.createReceipt({ task_id: task.task_id, action_fingerprint: "missing-target", capability: "write", args: {}, effect_class: "destructive" }), /governed target/i);
  assert.throws(() => receipts.createReceipt({ task_id: task.task_id, action_fingerprint: "bad-target", capability: "write", args: {}, target_ref: "C:\\temp", effect_class: "destructive" }), /governed target/i);
  assert.strictEqual(receipts.evaluateRecovery({ receipt: prepared, postcondition: "partial", authorityAllowsRetry: true, policyAllowsRetry: true }).decision, "rollback");
  receipts.transitionReceipt(prepared.receipt_id, "prepared", { preconditions: { state: "clean", target: "workspace:test" } });
  assert.strictEqual(receipts.getReceipt(prepared.receipt_id).preconditions.state, "clean");
  console.log("Agent receipt recovery: passed");
} finally { try { fs.rmSync(data, { recursive: true, force: true }); } catch {} }
