"use strict";
const assert = require("assert");
const fs = require("fs");
const os = require("os");
const path = require("path");
const data = fs.mkdtempSync(path.join(os.tmpdir(), "sidekick-agent-task-"));
process.env.SIDEKICK_DATA_DIR = data;
process.env.SIDEKICK_SECRET_KEY_FILE = path.join(data, "secret");
fs.writeFileSync(process.env.SIDEKICK_SECRET_KEY_FILE, "test-only-key");
const { createTask } = require("../src/agent/task-model");
const store = require("../src/agent/task-store");
try {
  const task = createTask({ task_id: "agt_store01", objective: "Inspect the service", profile: "quick" });
  const db = require("../src/db").getDb();
  assert.strictEqual(require("../src/agent/task-model").budgetExceeded({ ...task, created_at: new Date(Date.now() - task.budget.wall_ms - 1).toISOString() }, "wall_ms"), true);
  assert.strictEqual(store.insertTask(task).task_id, "agt_store01");
  assert.strictEqual(store.getTask("agt_store01").state, "created");
  const counted = store.incrementUsage("agt_store01", { tool_calls: 2, retries: 1 }, "test.usage");
  assert.strictEqual(counted.usage.tool_calls, 2);
  assert.strictEqual(counted.usage_ledger.retries, 1);
  assert.throws(() => store.incrementUsage("agt_store01", { tool_calls: 23 }, "test.over_budget"), /tool_calls budget exhausted/);
  assert.strictEqual(store.getTask("agt_store01").usage_ledger.tool_calls, 2, "failed accounting must be atomic");
  const child = createTask({ task_id: "agt_store02", root_task_id: "agt_store01", parent_task_id: "agt_store01", objective: "child", profile: "quick" });
  store.insertTask(child);
  const grandchild = createTask({ task_id: "agt_store03", root_task_id: "agt_store01", parent_task_id: "agt_store02", objective: "grandchild", profile: "quick" });
  store.insertTask(grandchild);
  assert.deepStrictEqual(store.listDescendants("agt_store01").map(item => item.task_id), ["agt_store01", "agt_store02", "agt_store03"], "descendant traversal is durable and ordered");
  store.incrementUsage(child.task_id, { tool_calls: 1 }, "test.child_usage");
  assert.strictEqual(store.getTask("agt_store01").usage_ledger.tool_calls, 3);
  assert.strictEqual(require("../src/agent/task-model").budgetExceeded(store.getTask(child.task_id), "tool_calls"), false);
  assert.ok(store.getTask(child.task_id).usage_ledger.wall_ms >= 0, "root wall-clock usage is persisted");
  const oldRootLedger = { ...store.getTask("agt_store01").usage_ledger, root_created_at: new Date(Date.now() - store.getTask("agt_store01").budget.wall_ms - 1).toISOString() };
  db.prepare("UPDATE agent_tasks SET usage_ledger_json=? WHERE task_id=?").run(JSON.stringify(oldRootLedger), "agt_store01");
  assert.strictEqual(require("../src/agent/task-model").budgetExceeded(store.getTask(child.task_id), "wall_ms"), true, "child wall budget is measured from the root task");
  const fanout = createTask({ task_id: "agt_fan01", objective: "fanout", profile: "standard" });
  store.insertTask(fanout);
  const reservations = [];
  for (let i = 0; i < 8; i++) reservations.push(store.reserveChildTask(fanout.task_id));
  assert.strictEqual(reservations.at(-1).remaining, 0, "the final governed child reservation exhausts the parent fan-out");
  assert.throws(() => store.reserveChildTask(fanout.task_id), /child-task envelope limit reached/, "the ninth concurrent-equivalent reservation must fail atomically");
  assert.strictEqual(store.getTask(fanout.task_id).usage_ledger.child_tasks, 8, "failed fan-out reservation does not consume root budget");
  store.updateTask("agt_store01", { state: "planning", phase: "planning", next_action: "draft_plan" });
  store.checkpointTask("agt_store01", { version: 1, safe_boundary: "after_goal", next_action: "draft_plan" });
  store.addPlanRevision("agt_store01", { version: 1, steps: [] });
  store.incrementUsage("agt_store01", { plan_revisions: 1 }, "test.plan_revision");
  assert.strictEqual(store.getTask("agt_store01").usage.plan_revisions, 1);
  store.addFailure("agt_store01", { action_fingerprint: "a", error_class: "timeout", retryable: true });
  store.recordCompletedOperation("agt_store01", { fingerprint: "read-fp", capability: "read", read_only: true, receipt_ref: "op-1", summary: "bounded read completed" });
  assert.strictEqual(store.getTask("agt_store01").continuation.completed_operations[0].receipt_ref, "op-1");
  store.recordAmbiguousOperation("agt_store01", { fingerprint: "write-fp", capability: "write", reason: "receipt unavailable" });
  assert.strictEqual(store.getTask("agt_store01").state, "blocked");
  const waitTask = createTask({ task_id: "agt_wait01", objective: "wait accounting", profile: "quick" });
  store.insertTask(waitTask);
  db.prepare("UPDATE agent_tasks SET state='waiting', phase='waiting', updated_at=? WHERE task_id=?").run(new Date(Date.now() - 1250).toISOString(), waitTask.task_id);
  const resumed = store.updateTask(waitTask.task_id, { state: "ready", phase: "recovery", next_action: "resume" }, "task.resumed");
  assert.ok(resumed.usage.waiting_ms >= 1000, "waiting time must be durably accounted");
  assert.ok(resumed.usage_ledger.waiting_ms >= 1000, "root waiting ledger must be durably accounted");
  const events = store.listEvents("agt_store01");
  assert.ok(events.some(event => event.event_type === "task.checkpoint"));
  assert.strictEqual(store.listTasks({ state: "blocked" }).length, 1);
  console.log("Agent task store: passed");
} finally { try { fs.rmSync(data, { recursive: true, force: true }); } catch {} }
