"use strict";
const assert = require("assert");
const fs = require("fs");
const os = require("os");
const path = require("path");
const data = fs.mkdtempSync(path.join(os.tmpdir(), "sidekick-agent-ops-"));
process.env.NODE_ENV = "test";
process.env.SIDEKICK_DATA_DIR = data;
process.env.SIDEKICK_SECRET_KEY_FILE = path.join(data, "secret");
fs.writeFileSync(process.env.SIDEKICK_SECRET_KEY_FILE, "test-only-key");
const { createTask } = require("../src/agent/task-model");
const tasks = require("../src/agent/task-store");
const ops = require("../src/agent/durable-operations");
try {
  const task = createTask({ task_id: "agt_ops01", objective: "inspect", profile: "standard", project_id: "project:test" });
  tasks.insertTask(task);
  for (const state of ["planning", "ready", "running", "verifying"]) tasks.updateTask(task.task_id, { state, phase: state }, "task.test_state");
  tasks.updateTask(task.task_id, { state: "completed", phase: "terminal", result: { status: "verified" }, verification: { status: "verified", recipe_gates: [{ recipe_id: "recipe:one", state: "satisfied" }] } }, "task.test_terminal");
  const derivedCandidates = ops.deriveLearningCandidates(task.task_id);
  assert.ok(derivedCandidates.some(candidate => candidate.kind === "budget_estimate"), "terminal project traces derive a bounded learning proposal");
  assert.ok(derivedCandidates.every(candidate => candidate.state === "proposal" && candidate.provenance.redacted === true), "derived learning remains redacted and inactive");
  assert.ok(derivedCandidates.every(candidate => candidate.candidate_version === 1), "derived learning candidates have a durable version");
  const plan = ops.savePlan(task.task_id, { objective: "inspect", milestones: [{ id: "m1" }], work_packages: [{ id: "p1" }], steps: [{ id: "s1", capability: "read", dependencies: [] }], verification_gates: [{ id: "g1", requirement_id: "r1" }] }, { source: "test" });
  assert.strictEqual(plan.revision, 1);
  assert.throws(() => ops.savePlan(task.task_id, { objective: "inspect", milestones: [{ id: "m1" }], work_packages: [{ id: "p1" }], steps: [{ id: "s1", capability: "read", dependencies: [] }], verification_gates: [{ id: "g1", requirement_id: "r1" }] }), /equivalent hierarchical plan/);
  assert.throws(() => ops.savePlan(task.task_id, { objective: "bad", steps: [{ id: "a", capability: "read", dependencies: ["b"] }, { id: "b", capability: "read", dependencies: ["a"] }] }), /cycle/i);
  assert.throws(() => ops.validatePlan({ objective: "bad", steps: [{ id: "x", capability: "" }] }), /governed/i);
  assert.throws(() => ops.validatePlan({ objective: "bad", work_packages: [{ id: "p1", command: "rm -rf" }] }), /executable/i);
  assert.throws(() => ops.validatePlan({ objective: "bad", verification_gates: [{ id: "g1", capability: "../../handler" }] }), /governed/i);
  assert.throws(() => ops.validatePlan({ objective: "bad", milestones: [{ id: "m1", verification_gate_ids: ["missing"] }], verification_gates: [] }), /unknown verification gate/i);
  const deepSteps = Array.from({ length: 18 }, (_, index) => ({ id: `deep_${index}`, capability: "read", dependencies: index ? [`deep_${index - 1}`] : [] })).reverse();
  assert.throws(() => ops.validatePlan({ objective: "deep", steps: deepSteps }), /depth/i);
  const fanoutSteps = [{ id: "root", capability: "read", dependencies: Array.from({ length: 33 }, (_, index) => `leaf_${index}`) }, ...Array.from({ length: 33 }, (_, index) => ({ id: `leaf_${index}`, capability: "read", dependencies: [] }))];
  assert.throws(() => ops.validatePlan({ objective: "fanout", steps: fanoutSteps }), /fan-out/i);
  const escalation = ops.createEscalation({ task_id: task.task_id, requested_operation: "delete target", reason: "ambiguous effect", target_ref: "artifact:target", expected_effect: "remove target", risk_class: "critical", effect_class: "destructive", pre_state: { observed: "partial" }, verification_plan: { capability: "read" }, rollback_plan: { available: false }, requested_scope: "single_operation" });
  assert.strictEqual(escalation.state, "open");
  assert.throws(() => ops.createEscalation({ task_id: task.task_id, requested_operation: "bad", reason: "bad", target_ref: "../../etc/passwd" }), /governed reference/);
  const normalizedEscalation = ops.createEscalation({ task_id: task.task_id, requested_operation: "inspect", reason: "unknown operation metadata", target_ref: "resource:target", risk_class: "low", effect_class: "read_only", requested_scope: "unbounded", approval_mode: "unbounded" });
  assert.strictEqual(normalizedEscalation.risk_class, "low");
  assert.strictEqual(normalizedEscalation.effect_class, "read_only");
  assert.strictEqual(normalizedEscalation.requested_scope, "single_operation");
  assert.strictEqual(normalizedEscalation.approval_mode, "single_operation");
  assert.throws(() => ops.updateEscalation(normalizedEscalation.escalation_id, "approved", { decided_by_principal_id: "principal:operator" }), /approval reference/);
  const resolvedEscalation = ops.updateEscalation(escalation.escalation_id, "resolved", { decided_by_principal_id: "principal:operator", approval_ref: "approval:test" });
  assert.strictEqual(resolvedEscalation.state, "resolved");
  assert.strictEqual(resolvedEscalation.decided_by_principal_id, "principal:operator");
  assert.strictEqual(resolvedEscalation.approval_ref, "approval:test");
  const repairId = ops.recordRepair({ task_id: task.task_id, failure_class: "transient", capability: "read", argument_digest: "digest", retry_decision: "bounded_retry", strategy: "changed condition" });
  assert.ok(repairId);
  const workPackage = ops.createWorkPackage({ task_id: task.task_id, package_key: "inspect-repository", mutation_target: "repository:sidekick" });
  assert.strictEqual(ops.claimWorkPackage(workPackage.package_id, "worker-1").state, "running");
  assert.strictEqual(tasks.getTask(task.task_id).usage_ledger.concurrent_operations, 1, "claim durably increments root concurrent-operation usage");
  const concurrentPackage = ops.createWorkPackage({ task_id: task.task_id, package_key: "independent-read" });
  assert.throws(() => ops.claimWorkPackage(concurrentPackage.package_id, "worker-2"), /concurrency limit/);
  ops.finishWorkPackage(workPackage.package_id, "completed", { ok: true }, "worker-1");
  assert.strictEqual(tasks.getTask(task.task_id).usage_ledger.concurrent_operations, 0, "finish durably decrements root concurrent-operation usage");
  assert.strictEqual(ops.claimWorkPackage(concurrentPackage.package_id, "worker-2").state, "running");
  const recoveredRead = ops.recoverExpiredWorkPackages("2999-01-01T00:00:00.000Z");
  assert.ok(recoveredRead.queued.includes(concurrentPackage.package_id), "expired read package is safely requeued");
  assert.strictEqual(tasks.getTask(task.task_id).usage_ledger.concurrent_operations, 0, "expiry recovery releases concurrent-operation usage");
  const mutationPackage = ops.createWorkPackage({ task_id: task.task_id, package_key: "mutation-package", mutation_target: "repository:sidekick" });
  assert.strictEqual(ops.claimWorkPackage(mutationPackage.package_id, "worker-3").state, "running");
  assert.throws(() => ops.createWorkPackage({ task_id: task.task_id, package_key: "same-target", mutation_target: "repository:sidekick" }), /mutation target/);
  const recoveredMutation = ops.recoverExpiredWorkPackages("2999-01-01T00:00:00.000Z");
  assert.ok(recoveredMutation.parked.includes(mutationPackage.package_id), "expired mutation package is parked rather than replayed");
  const candidate = ops.createLearningCandidate({ project_ref: "project:test", kind: "repair_strategy", source_task_id: task.task_id, proposal: { strategy: "bounded" }, provenance: { task_id: task.task_id } });
  assert.strictEqual(candidate.state, "proposal");
  const replay = ops.evaluateLearningCandidate(candidate.candidate_id);
  assert.strictEqual(replay.evaluation.method, "bounded_historical_trace_replay");
  assert.strictEqual(replay.evaluation.policy_impact.authority_expansion, false);
  assert.ok(replay.evaluation.comparison);
  assert.strictEqual(ops.getLearningCandidate(candidate.candidate_id).evaluation.executable_activation, false);
  assert.throws(() => ops.updateLearningCandidate(candidate.candidate_id, "active", {}), /approval/);
  assert.strictEqual(ops.updateLearningCandidate(candidate.candidate_id, "trial", { approved_by: "operator:test" }).state, "trial");
  assert.throws(() => ops.createLearningCandidate({ project_ref: "other", kind: "repair_strategy", proposal: {} }), /governed project/);
  const receipts = require("../src/agent/receipt-store");
  const receipt = receipts.createReceipt({ task_id: task.task_id, action_fingerprint: "fingerprint-1", capability: "write", args: { target: "artifact:target" }, idempotency_class: "idempotent", reversibility_class: "reversible" });
  assert.strictEqual(receipts.evaluateRecovery({ receipt, postcondition: "absent", authorityAllowsRetry: true, policyAllowsRetry: true }).decision, "retry");
  assert.strictEqual(receipts.evaluateRecovery({ receipt, postcondition: "unknown", authorityAllowsRetry: true, policyAllowsRetry: true }).decision, "escalate");
  const recipeId = receipts.createRecipe({ task_id: task.task_id, requirement_id: "r1", check_type: "read", capability: "read", arguments: {}, expected: {} });
  assert.ok(receipts.recordOutcome({ recipe_id: recipeId, task_id: task.task_id, summary: "safe evidence" }).startsWith("avo_"));
  assert.strictEqual(receipts.listOutcomes(task.task_id).length, 1);
  console.log("Agent durable operations: passed");
} finally { try { fs.rmSync(data, { recursive: true, force: true }); } catch {} }
