"use strict";
const { requireFromSidekick } = require("./deps");
const { z } = requireFromSidekick("zod");
const result = value => ({ content: [{ type: "text", text: JSON.stringify(value, null, 2) }] });
async function call(services, name, args) { const value = await services.dispatch(name, args); if (value?.isError) throw Object.assign(new Error(`${name} dependency failed`), { code: value.code || "dependency_failed", dependency: name }); return value; }
function successful(value) {
  if (!value || value.isError) return false;
  const parsed = decode(value);
  return parsed?.ok === true || parsed?.ok === 1;
}
function decode(value) { if (value && typeof value === "object" && !value.content) return value; try { return JSON.parse(value?.content?.map(item => item.text || "").join("\n") || ""); } catch { return null; } }
function normalize(value) { const parsed = decode(value); if (!parsed || typeof parsed !== "object") return { state: "unavailable", verdict: "unavailable", ok: false, errors: ["dependency returned invalid JSON"], commands: [] }; const verdict = parsed.verdict || parsed.summary?.verdict || (parsed.ok === true ? "passed" : parsed.ok === false ? "failed" : "unknown"); const state = value?.isError ? "unavailable" : parsed.state === "unavailable" ? "unavailable" : "available"; return { state, verdict: state === "unavailable" ? "unavailable" : verdict, ok: state === "available" && ["passed", "passed_partial"].includes(verdict), commands: Array.isArray(parsed.commands) ? parsed.commands : Array.isArray(parsed.selected) ? parsed.selected : [], raw_shape: Object.keys(parsed).sort() }; }
async function gate(services, args) {
  const mode = args.mode || services.config?.default_mode || "standard";
  const verification = await call(services, "dev_verify", { path: args.path, mode, intents: args.intents, continue_on_failure: args.continue_on_failure === true, max_output_chars: args.max_output_chars || services.config?.max_output_chars || 12000, timeout_ms: args.timeout_ms || 600000, dry_run: args.dry_run === true });
  const profile = await call(services, "dev_repo_profile", { path: args.path, include_git: true, include_semantic: false });
  const semantic = await call(services, "semantic_repo", { path: args.path, action: "verify" });
   const normalized = { verification: normalize(verification), repository: normalize(profile), semantic_index: normalize(semantic) }; return result({ ok: Object.values(normalized).every(item => item.ok), state: Object.values(normalized).every(item => item.state === "available") ? "available" : "unavailable", ...normalized, deterministic_gate: "verification result and semantic index integrity are reported separately", raw_results_available: true });
}
async function lifecycle(services, args) { if (args.action === "cancel") return result({ ok: false, state: "unavailable", code: "cancellation_unsupported", error: "dev_verify exposes no cancellation handle; no command was repeated or fabricated" }); try { const value = await services.dispatch("dev_verify", { path: args.path, mode: args.mode, intents: args.intents, dry_run: args.action === "plan" }); return result({ ok: !value?.isError, state: value?.isError ? "unavailable" : "available", action: args.action, result: normalize(value), raw_result: value }); } catch (error) { return result({ ok: false, state: "unavailable", code: "verification_unavailable", error: String(error.message || error).slice(0, 300) }); } }
async function health(services) { const checks = {}; for (const [name, args] of [["dev_verify", { path: process.cwd(), dry_run: true, intents: ["syntax"] }], ["dev_repo_profile", { path: process.cwd(), include_git: false, include_semantic: false }], ["semantic_repo", { path: process.cwd(), action: "verify" }]]) { try { await call(services, name, args); checks[name] = true; } catch { checks[name] = false; } } return result({ ok: Object.values(checks).every(Boolean), checks, writes: false }); }
const entry = { buildDescriptors(services) { return [
   { name: "quality_gate", description: "Run or plan bounded project verification and independently verify the semantic repository index.", schema: z.object({ path: z.string().min(1).max(2048), mode: z.enum(["quick", "standard", "full"]).optional(), intents: z.array(z.enum(["syntax", "lint", "typecheck", "test", "build"])).min(1).max(5).optional(), continue_on_failure: z.boolean().optional(), max_output_chars: z.number().int().min(500).max(60000).optional(), timeout_ms: z.number().int().min(1000).max(600000).optional(), dry_run: z.boolean().optional() }).strict(), args: { path: "string", mode: "string", intents: "array", dry_run: "boolean" }, risk: "high", category: "Development", handler: async args => { try { return await gate(services, args); } catch (error) { return result({ ok: false, state: "unavailable", code: error.code || "quality_dependency_failed", dependency: error.dependency || null, error: String(error.message || error).slice(0, 300) }); } } },
   { name: "quality_health", description: "Probe verification, repository profiling and semantic-index dependencies without executing project tests.", schema: z.object({}), args: {}, risk: "low", category: "Development", annotations: { readOnlyHint: true, idempotentHint: true }, handler: () => health(services) },
   { name: "quality_result_normalize", description: "Normalize governed verification output into stable state, verdict and command fields without changing the underlying evidence.", schema: z.object({ result: z.any() }).strict(), args: { result: "object" }, risk: "low", category: "Development", handler: args => result(normalize(args.result)) },
   { name: "quality_lifecycle", description: "Plan or execute a bounded verification request and report unavailable or unsupported cancellation honestly.", schema: z.object({ action: z.enum(["plan", "execute", "cancel"]), path: z.string().min(1).max(2048), mode: z.enum(["quick", "standard", "full"]).optional(), intents: z.array(z.enum(["syntax", "lint", "typecheck", "test", "build"])).max(5).optional() }).strict(), args: { action: "string", path: "string", mode: "string", intents: "array" }, risk: "high", category: "Development", handler: args => lifecycle(services, args) },
]; }, healthCheck({ config }) { return { ok: ["quick", "standard", "full"].includes(config?.default_mode || "standard"), details: { default_mode: config?.default_mode || "standard", dependencies: ["dev_verify", "dev_repo_profile", "semantic_repo"], project_execution: "only through dev_verify" } }; } };
module.exports = { entry, buildDescriptors: entry.buildDescriptors, healthCheck: entry.healthCheck };
