"use strict";
const crypto = require("crypto");
const dbStore = require("../db");
const { redactSensitive, redactSensitiveKeysDeep, isSensitiveKey } = require("../redact");
const { argumentDigest, governedTargetRef } = require("./authority");
const id = p => `${p}_${crypto.randomBytes(10).toString("hex")}`;
const now = () => new Date().toISOString();
const GOVERNED_REF = /^(?:workspace|repository|project|artifact|resource|service|job|operation|task):[A-Za-z0-9_.:/-]{1,240}$/;
const safe = value => JSON.stringify(redactSensitiveKeysDeep(value || {}));
function boundedSafe(value, label, maxBytes = 16000, depth = 0) {
  if (depth > 8) throw new Error(`${label} is too deeply nested`);
  if (Array.isArray(value)) {
    if (value.length > 128) throw new Error(`${label} contains too many items`);
    value.forEach(item => boundedSafe(item, label, maxBytes, depth + 1));
  } else if (value && typeof value === "object") {
    const keys = Object.keys(value);
    if (keys.length > 128) throw new Error(`${label} contains too many fields`);
    keys.forEach(key => boundedSafe(value[key], label, maxBytes, depth + 1));
  } else if (typeof value === "string" && value.length > 4000) {
    throw new Error(`${label} contains an oversized string`);
  }
  const serialized = JSON.stringify(value == null ? null : value);
  if (serialized && serialized.length > maxBytes) throw new Error(`${label} is too large`);
  return value;
}
function ensure() { try { dbStore.getDb().prepare("SELECT receipt_id FROM agent_operation_receipts LIMIT 1").get(); } catch { dbStore.runPendingMigrations(); } }
function retrySafe(value, key = "") { if (isSensitiveKey(key)) return false; if (Array.isArray(value)) return value.every(item => retrySafe(item)); if (value && typeof value === "object") return Object.entries(value).every(([k,v]) => retrySafe(v,k)); return typeof value !== "string" || redactSensitive(value) === value; }
function createRetryRecipe(input = {}) { ensure(); boundedSafe(input.arguments || {}, "retry recipe arguments", 12000); const targetRef=String(input.target_ref||"").trim(); if (!input.task_id || !input.capability || !GOVERNED_REF.test(targetRef) || !retrySafe(input.arguments)) throw new Error("retry recipe requires safe arguments and a governed target reference"); const serialized=JSON.stringify(redactSensitiveKeysDeep(input.arguments||{})); if(serialized.length>12000) throw new Error("retry recipe is too large"); const recipe_id=input.recipe_id||id("arr"),t=now(); dbStore.getDb().prepare("INSERT INTO agent_retry_recipes (recipe_id,task_id,version,capability,arguments_json,target_ref,created_at) VALUES (?,?,?,?,?,?,?)").run(recipe_id,input.task_id,1,String(input.capability),serialized,targetRef,t); return getRetryRecipe(recipe_id); }
function getRetryRecipe(recipeId) { ensure(); const r=dbStore.getDb().prepare("SELECT * FROM agent_retry_recipes WHERE recipe_id=?").get(recipeId); return r?{...r,arguments:parse(r.arguments_json,{})}:null; }
function createReceipt(input = {}) { ensure(); boundedSafe(input.preconditions || {}, "receipt preconditions", 12000); boundedSafe(input.expected_postconditions || [], "receipt postconditions", 12000); if (!input.task_id || !input.capability || !input.action_fingerprint) throw new Error("task, capability, and fingerprint are required"); const explicitTarget = input.target_ref == null ? null : String(input.target_ref).trim(); if (explicitTarget && !GOVERNED_REF.test(explicitTarget)) throw new Error("receipt target must be a governed target reference"); const targetRef = governedTargetRef(input.args || {}, explicitTarget); const effectClass = String(input.effect_class || "unknown"); if (effectClass !== "read_only" && !targetRef) throw new Error("mutating receipt requires a governed target reference"); const t=now(), receipt_id=input.receipt_id || id("aor"); const db=dbStore.getDb(); db.prepare(`INSERT INTO agent_operation_receipts (receipt_id,task_id,version,action_fingerprint,capability,capability_version,argument_digest,target_ref,project_ref,workspace_ref,risk_class,effect_class,idempotency_class,reversibility_class,preconditions_json,dispatch_state,dispatched_at,finalized_at,provider_receipt_ref,expected_postconditions_json,verification_recipe_ref,rollback_recipe_ref,retry_recipe_ref,outcome_state,principal_ref,policy_ref,approval_ref,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(receipt_id,input.task_id,1,String(input.action_fingerprint),String(input.capability),input.capability_version||null,argumentDigest(input.args||{}),targetRef,input.project_ref||null,input.workspace_ref||null,input.risk_class||"critical",effectClass,input.idempotency_class||"unknown",input.reversibility_class||"unknown",safe(input.preconditions),"prepared",null,null,null,safe(input.expected_postconditions||[]),input.verification_recipe_ref||null,input.rollback_recipe_ref||null,input.retry_recipe_ref||null,"pending",input.principal_ref||null,input.policy_ref||null,input.approval_ref||null,t,t); return getReceipt(receipt_id); }
function getReceipt(receiptId) { ensure(); const r=dbStore.getDb().prepare("SELECT * FROM agent_operation_receipts WHERE receipt_id=?").get(receiptId); return r ? {...r,preconditions:parse(r.preconditions_json,{}),expected_postconditions:parse(r.expected_postconditions_json,[])} : null; }
function parse(v,f){try{return v?JSON.parse(v):f;}catch{return f;}}
function transitionReceipt(receiptId, state, patch={}) { ensure(); const transitions={prepared:new Set(["dispatched","awaiting_approval","failed"]),awaiting_approval:new Set(["dispatched","failed"]),dispatched:new Set(["awaiting_approval","finalized","ambiguous","failed"]),ambiguous:new Set(["verified","rolled_back","failed"]),finalized:new Set(["verified"]),verified:new Set([]),rolled_back:new Set([]),failed:new Set([])}; const allowed=new Set(Object.keys(transitions)); if(!allowed.has(state)) throw new Error("invalid receipt state"); const current=getReceipt(receiptId); if(!current)throw new Error("receipt not found"); const currentState=current.dispatch_state || "prepared"; if(currentState!==state && !transitions[currentState]?.has(state))throw new Error(`invalid receipt transition: ${currentState} -> ${state}`); const t=now(); const fields=[state,patch.provider_receipt_ref||null,state==="dispatched"?t:null,state==="finalized"||state==="verified"?t:null,patch.preconditions===undefined?null:safe(patch.preconditions),patch.approval_ref||null,t,receiptId]; dbStore.getDb().prepare("UPDATE agent_operation_receipts SET dispatch_state=?,outcome_state=?,provider_receipt_ref=COALESCE(?,provider_receipt_ref),dispatched_at=COALESCE(?,dispatched_at),finalized_at=COALESCE(?,finalized_at),preconditions_json=COALESCE(?,preconditions_json),approval_ref=COALESCE(?,approval_ref),updated_at=? WHERE receipt_id=?").run(fields[0],fields[0],fields[1],fields[2],fields[3],fields[4],fields[5],fields[6],fields[7]); return getReceipt(receiptId); }
function evaluateRecovery({ receipt, postcondition, targetState = "unknown", authorityAllowsRetry = false, policyAllowsRetry = false } = {}) { if (!receipt) return { decision: "escalate", reason: "operation receipt is unavailable" }; if (receipt.outcome_state === "finalized" || receipt.outcome_state === "verified") return { decision: "completed", reason: "receipt is already finalized" }; if (postcondition === "satisfied") return { decision: "completed", reason: "fresh governed observation satisfies the expected postcondition" }; if (postcondition === "absent" && receipt.idempotency_class === "idempotent" && authorityAllowsRetry && policyAllowsRetry && targetState !== "ambiguous") return { decision: "retry", reason: "fresh observation proves absence and retry is authoritatively safe" }; if (postcondition === "partial" && receipt.reversibility_class === "reversible" && authorityAllowsRetry && policyAllowsRetry) return { decision: "rollback", reason: "fresh observation found partial state and authorized rollback is available" }; return { decision: "escalate", reason: "operation effect remains ambiguous or retry is not authorized" }; }
function listReceipts(taskId){ensure();return dbStore.getDb().prepare("SELECT * FROM agent_operation_receipts WHERE task_id=? ORDER BY created_at ASC").all(taskId).map(r=>({...r,preconditions:parse(r.preconditions_json,{}),expected_postconditions:parse(r.expected_postconditions_json,[])}));}
function createRecipe(input={}){ensure();boundedSafe(input.arguments || {}, "verification arguments", 12000);boundedSafe(input.expected || {}, "verification expectation", 8000);boundedSafe(input.retry_policy || {}, "verification retry policy", 4000);const t=now(),recipe_id=input.recipe_id||id("avr");dbStore.getDb().prepare("INSERT INTO agent_verification_recipes (recipe_id,task_id,version,requirement_id,check_type,capability,arguments_json,expected_json,freshness_ms,independent,timeout_ms,retry_policy_json,failure_classification,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(recipe_id,input.task_id,1,String(input.requirement_id),String(input.check_type),String(input.capability),safe(input.arguments),safe(input.expected),Math.max(0,Math.min(86400000,Number(input.freshness_ms)||300000)),input.independent===true?1:0,Math.max(100,Math.min(120000,Number(input.timeout_ms)||30000)),safe(input.retry_policy),String(input.failure_classification||"verification_failed").slice(0,120),t);return recipe_id;}
function listRecipes(taskId){ensure();return dbStore.getDb().prepare("SELECT * FROM agent_verification_recipes WHERE task_id=? ORDER BY created_at ASC").all(taskId).map(r=>({...r,arguments:parse(r.arguments_json,{}),expected:parse(r.expected_json,{})}));}
function getRecipe(recipeId){ensure();const r=dbStore.getDb().prepare("SELECT * FROM agent_verification_recipes WHERE recipe_id=?").get(recipeId);return r?{...r,arguments:parse(r.arguments_json,{}),expected:parse(r.expected_json,{})}:null;}
function recordOutcome(input={}){ensure();const t=now(),outcome_id=id("avo");dbStore.getDb().prepare("INSERT INTO agent_verification_outcomes (outcome_id,recipe_id,task_id,evidence_ref,freshness_state,independence_state,observation_state,summary,observed_at) VALUES (?,?,?,?,?,?,?,?,?)").run(outcome_id,input.recipe_id,input.task_id,input.evidence_ref||null,input.freshness_state||"fresh",input.independence_state||"independent",input.observation_state||"unavailable",redactSensitive(String(input.summary||"")).slice(0,1000),t);return outcome_id;}
function listOutcomes(taskId){ensure();return dbStore.getDb().prepare("SELECT * FROM agent_verification_outcomes WHERE task_id=? ORDER BY observed_at DESC LIMIT 200").all(taskId).map(row=>({...row,summary:redactSensitive(row.summary)}));}
module.exports={createReceipt,getReceipt,transitionReceipt,evaluateRecovery,listReceipts,createRetryRecipe,getRetryRecipe,createRecipe,listRecipes,getRecipe,recordOutcome,listOutcomes};
