"use strict";

const crypto = require("crypto");
const dbStore = require("../db");
const { redactSensitive, redactSensitiveKeysDeep } = require("../redact");
const model = require("./task-model");

const MAX_LIST = 100;
const json = value => JSON.stringify(redactSensitiveKeysDeep(value));
const parse = (value, fallback) => { try { return value ? JSON.parse(value) : fallback; } catch { return fallback; } };
const now = () => new Date().toISOString();
const id = prefix => `${prefix}_${crypto.randomBytes(10).toString("hex")}`;

function rowToTask(row) {
  if (!row) return null;
  return { ...row, goal: parse(row.goal_json, {}), requirements: parse(row.requirements_json, []), budget: parse(row.budget_json, {}), usage: parse(row.usage_json, {}), checkpoint: parse(row.checkpoint_json, {}), control: parse(row.control_json, {}), continuation: parse(row.continuation_json, { version: 1, completed_operations: [], ambiguous_operations: [] }), artifact_refs: parse(row.artifact_refs_json, []), result: parse(row.result_json, null), verification: parse(row.verification_json, null), schema_version: row.schema_version };
}
function ensureTaskSchema() {
  try { dbStore.getDb().prepare("SELECT task_id FROM agent_tasks LIMIT 1").get(); return; } catch (error) {
    if (typeof dbStore.runPendingMigrations === "function") dbStore.runPendingMigrations();
    dbStore.getDb().prepare("SELECT task_id FROM agent_tasks LIMIT 1").get();
  }
}
function insertTask(task) {
  ensureTaskSchema();
  const db = dbStore.getDb();
  const tx = db.transaction(() => {
    db.prepare(`INSERT INTO agent_tasks (task_id,root_task_id,parent_task_id,session_id,execution_id,project_id,actor_id,requested_by_principal_id,actor_principal_id,acting_for_principal_id,objective,normalized_objective,goal_json,profile,state,phase,current_plan_revision,requirements_json,budget_json,usage_json,workspace_ref,model_version,prompt_version,policy_version,capability_registry_version,schema_version,checkpoint_json,next_action,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(task.task_id, task.root_task_id, task.parent_task_id, task.session_id, task.execution_id, task.project_id, task.actor_id, task.requested_by_principal_id, task.actor_principal_id, task.acting_for_principal_id, redactSensitive(task.objective), redactSensitive(task.normalized_objective), json(task.goal), task.profile, task.state, task.phase, task.current_plan_revision, json(task.requirements), json(task.budget), json(task.usage), task.workspace_ref, task.model_version, task.prompt_version, task.policy_version, task.capability_registry_version, task.schema_version, json(task.checkpoint), redactSensitive(task.next_action), task.created_at, task.updated_at);
    appendEventInternal(db, task.task_id, "task.created", task.actor_id, { state: task.state, profile: task.profile });
  });
  tx();
  return getTask(task.task_id);
}
function appendEventInternal(db, taskId, eventType, actorId, payload) { db.prepare("INSERT INTO agent_task_events (event_id,task_id,event_type,actor_id,payload_json,created_at) VALUES (?,?,?,?,?,?)").run(id("ate"), taskId, eventType, actorId || null, json(payload || {}), now()); }
function getTask(taskId) { ensureTaskSchema(); return rowToTask(dbStore.getDb().prepare("SELECT * FROM agent_tasks WHERE task_id = ?").get(String(taskId))); }
function listTasks({ project_id, state, limit = 50, offset = 0 } = {}) { ensureTaskSchema(); const where = [], params = []; if (project_id) { where.push("project_id = ?"); params.push(project_id); } if (state) { where.push("state = ?"); params.push(state); } const bounded = Math.min(Math.max(Number(limit) || 50, 1), MAX_LIST); const skip = Math.max(Number(offset) || 0, 0); const rows = dbStore.getDb().prepare(`SELECT * FROM agent_tasks ${where.length ? `WHERE ${where.join(" AND ")}` : ""} ORDER BY updated_at DESC LIMIT ? OFFSET ?`).all(...params, bounded, skip); return rows.map(rowToTask); }
function updateTask(taskId, patch, eventType = "task.updated") {
  const current = getTask(taskId); if (!current) return null; if (model.TERMINAL.has(current.state) && patch.state && patch.state !== current.state) throw new Error("terminal task cannot be changed");
  const next = { ...current, ...patch, updated_at: now() }; if (patch.state && patch.state !== current.state) model.transition(current, patch.state, next.updated_at);
  const db = dbStore.getDb(); const tx = db.transaction(() => { db.prepare(`UPDATE agent_tasks SET execution_id=COALESCE(?,execution_id),state=?,phase=?,current_plan_revision=?,requirements_json=?,budget_json=?,usage_json=?,workspace_ref=?,checkpoint_json=?,next_action=?,control_json=?,continuation_json=?,artifact_refs_json=?,result_json=?,verification_json=?,last_error_code=?,updated_at=?,completed_at=? WHERE task_id=?`).run(next.execution_id || null, next.state, next.phase, next.current_plan_revision, json(next.requirements), json(next.budget), json(next.usage), next.workspace_ref, json(next.checkpoint), redactSensitive(next.next_action), json(next.control || {}), json(next.continuation || {}), json(next.artifact_refs || []), next.result == null ? null : json(next.result), next.verification == null ? null : json(next.verification), next.last_error_code || null, next.updated_at, next.completed_at || null, taskId); appendEventInternal(db, taskId, eventType, next.actor_id, { state: next.state, phase: next.phase, next_action: next.next_action }); }); tx(); return getTask(taskId);
}
function checkpointTask(taskId, checkpoint) { const task = getTask(taskId); if (!task) throw new Error("task not found"); const safe = model.assertCheckpoint(task, checkpoint); return updateTask(taskId, { checkpoint: safe, next_action: safe.next_action }, "task.checkpoint"); }
function addPlanRevision(taskId, plan, source = "planner") { const task = getTask(taskId); if (!task) throw new Error("task not found"); if (!plan || typeof plan !== "object" || Array.isArray(plan)) throw new Error("plan must be an object"); const revision = task.current_plan_revision + 1; const db = dbStore.getDb(); db.prepare("INSERT INTO agent_task_plan_revisions (task_id,revision,plan_json,source,created_at) VALUES (?,?,?,?,?)").run(taskId, revision, json(plan), String(source).slice(0, 100), now()); return updateTask(taskId, { current_plan_revision: revision }, "task.plan_revision"); }
function addFailure(taskId, failure) { const task = getTask(taskId); if (!task) throw new Error("task not found"); const record = { ...failure, failure_id: id("atf"), action_fingerprint: String(failure.action_fingerprint || "").slice(0, 128), capability: failure.capability ? String(failure.capability).slice(0, 120) : null, error_class: String(failure.error_class || "unknown").slice(0, 80), retryable: failure.retryable === true ? 1 : 0, attempt: Math.max(1, Number(failure.attempt) || 1), changed_condition: failure.changed_condition === true ? 1 : 0, detail: redactSensitive(String(failure.detail || "")).slice(0, 2000), created_at: now() }; dbStore.getDb().prepare("INSERT INTO agent_task_failures (failure_id,task_id,action_fingerprint,capability,error_class,retryable,attempt,changed_condition,detail,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)").run(record.failure_id, taskId, record.action_fingerprint, record.capability, record.error_class, record.retryable, record.attempt, record.changed_condition, record.detail, record.created_at); const usage = { ...task.usage, failures: Number(task.usage.failures || 0) + 1 }; return updateTask(taskId, { usage }, "task.failure"); }
function saveResult(taskId, result, verification) { const normalized = model.validateResult(result); return updateTask(taskId, { result: normalized, verification: verification || null, phase: "complete", next_action: null, state: normalized.status === "verified" ? "completed" : "partial" }, "task.result"); }
function listEvents(taskId, limit = 100) { ensureTaskSchema(); return dbStore.getDb().prepare("SELECT event_id,task_id,event_type,actor_id,payload_json,created_at FROM agent_task_events WHERE task_id = ? ORDER BY created_at ASC,event_id ASC LIMIT ?").all(taskId, Math.min(Math.max(Number(limit) || 100, 1), 500)).map(row => ({ ...row, payload: parse(row.payload_json, {}) })); }
function listPlans(taskId) { ensureTaskSchema(); return dbStore.getDb().prepare("SELECT task_id,revision,plan_json,source,created_at FROM agent_task_plan_revisions WHERE task_id = ? ORDER BY revision DESC LIMIT 100").all(taskId).map(row => ({ ...row, plan: parse(row.plan_json, {}) })); }
function listFailures(taskId) { ensureTaskSchema(); return dbStore.getDb().prepare("SELECT failure_id,task_id,action_fingerprint,capability,error_class,retryable,attempt,changed_condition,detail,created_at FROM agent_task_failures WHERE task_id = ? ORDER BY created_at DESC LIMIT 100").all(taskId); }
function recordGuidance(taskId, guidance, actorId = "user") { const task = getTask(taskId); if (!task) throw new Error("task not found"); const message = redactSensitive(String(guidance || "").trim()).slice(0, 2000); if (!message) throw new Error("guidance is required"); const db = dbStore.getDb(); db.transaction(() => appendEventInternal(db, taskId, "task.user_guidance", actorId, { guidance: message }))(); return getTask(taskId); }
function recordChildRequest(taskId, childTaskId, kind, actorId = "user") { const task = getTask(taskId); if (!task) throw new Error("task not found"); const db = dbStore.getDb(); db.transaction(() => appendEventInternal(db, taskId, "task.child_requested", actorId, { child_task_id: String(childTaskId).slice(0, 80), kind: String(kind || "continue").slice(0, 80) }))(); return task; }
function recordCompletedOperation(taskId, operation = {}) { const task = getTask(taskId); if (!task) throw new Error("task not found"); const continuation = task.continuation || { version: 1, completed_operations: [], ambiguous_operations: [] }; const item = { fingerprint: String(operation.fingerprint || "").slice(0, 128), capability: String(operation.capability || "").slice(0, 120), read_only: operation.read_only === true, receipt_ref: operation.receipt_ref ? redactSensitive(String(operation.receipt_ref)).slice(0, 300) : null, summary: redactSensitive(String(operation.summary || "")).slice(0, 500), completed_at: now() }; if (!item.fingerprint || !item.capability) throw new Error("operation fingerprint and capability are required"); const completed = [...(continuation.completed_operations || []).filter(row => row.fingerprint !== item.fingerprint), item].slice(-100); return updateTask(taskId, { continuation: { version: 1, completed_operations: completed, ambiguous_operations: continuation.ambiguous_operations || [] } }, "task.operation_completed"); }
function recordAmbiguousOperation(taskId, operation = {}) { const task = getTask(taskId); if (!task) throw new Error("task not found"); const continuation = task.continuation || { version: 1, completed_operations: [], ambiguous_operations: [] }; const item = { fingerprint: String(operation.fingerprint || "").slice(0, 128), capability: String(operation.capability || "").slice(0, 120), reason: redactSensitive(String(operation.reason || "")).slice(0, 500), created_at: now() }; const ambiguous = [...(continuation.ambiguous_operations || []).filter(row => row.fingerprint !== item.fingerprint), item].slice(-100); return updateTask(taskId, { continuation: { version: 1, completed_operations: continuation.completed_operations || [], ambiguous_operations: ambiguous }, state: "blocked", phase: "recovery", next_action: "verify_ambiguous_operation" }, "task.operation_ambiguous"); }
module.exports = { insertTask, getTask, listTasks, updateTask, checkpointTask, addPlanRevision, addFailure, saveResult, listEvents, listPlans, listFailures, recordGuidance, recordChildRequest, recordCompletedOperation, recordAmbiguousOperation, ensureTaskSchema };
