"use strict";

// Compute administration tools are ordinary governed descriptors. They share
// the same dispatcher, policy, approval, audit, placement, and artifact
// custody path as every other tool; this family only owns registration data
// and binds the existing Compute handlers.
const computeTools = require("../../compute/tools");
const { TOOL_SCHEMAS } = require("../schemas");

const definitions = [
  ["compute", "Sidekick Compute: provider-neutral inference and compute system. List providers, check health, get system overview.", { action: "string (overview|init)" }, computeTools.sidekick_compute, "medium"],
  ["compute_nodes", "Manage compute worker nodes, local-only telemetry, and enrollment tokens: list, get, telemetry, heartbeat, revoke, maintenance mode, stats, create/list tokens, enroll", { action: "string (list|get|telemetry|heartbeat|revoke|maintenance|stats|create_token|list_tokens|enroll)", node_id: "string (worker node ID for get/telemetry/heartbeat/revoke/maintenance/enroll)", worker_id: "string (worker ID for telemetry or dashboard lifecycle actions)", token: "string (enrollment token for enroll)", display_name: "string (worker or token display name)", platform: "string (worker platform for enroll or telemetry filter)", architecture: "string (optional, worker architecture)", reason: "string (optional, revoke reason)", enable: "boolean (optional, maintenance action: true returns worker to enabled service; false places it into maintenance)", state: "string (optional, filter by worker state for list/telemetry)", hardware_type: "string (optional, filter by hardware_type for list)", provider: "string (optional, filter by provider for list)", trust_level: "string (optional, filter by trust level for telemetry)" }, computeTools.sidekick_compute_nodes, "medium"],
  ["compute_providers", "Manage compute providers (Ollama, OpenAI, vLLM, etc.): list, get, create, update, delete, health check", { action: "string (list|get|create|update|delete|health|health_all)", provider_id: "string (provider ID for get/update/delete/health)", name: "string (display name; required for create)", type: "string (provider type; required for create: ollama|openai|vllm|llamacpp|mlx; filters list)", base_url: "string (base URL for create/update)", api_key: "string (optional, recorded but NOT used to authenticate — no adapter reads it; do not paste a live credential)", priority: "number (optional, placement priority; HIGHER wins, default 50)", enabled: "boolean (optional, enable/disable; filters list)", trust_level: "string (optional placement gate: untrusted|limited|trusted|privileged; registry default 'private' ranks equal to trusted)", capabilities: "string[] (optional, descriptive only — placement gates on MODEL capabilities)", mode: "string (optional, direct|worker, default direct)", tls_policy: "string (optional, require|prefer|off, default prefer)", cost_policy: "string (optional, default free)", data_classifications: "string[] (optional placement gate: public|internal|private|sensitive|restricted; default public/internal/private)" }, computeTools.sidekick_compute_providers, "high"],
  ["compute_models", "Manage compute models: list, get, create, update, delete, discover from providers. Note: discover only LISTS what a provider currently serves — it does not register anything; use create to add a model to the registry", { action: "string (list|get|create|update|delete|discover)", model_id: "string (model ID for get/update/delete)", provider_id: "string (required for create; filters list)", model_name: "string (display name; required for create)", provider_model_name: "string (name on the provider, e.g. qwen3.5:latest; required for create)", family: "string (optional, stored as metadata)", parameter_count: "string (optional, e.g. 7b, 13b, 70b; stored as metadata)", context_length: "number (optional, context window size)", supports_vision: "boolean (optional; filters list)", supports_tools: "boolean (optional)", supports_embedding: "boolean (optional; filters list)", supports_structured_output: "boolean (optional)", min_vram_gb: "number (optional, minimum VRAM in GB)", capabilities: "string[] (optional, e.g. chat, generate, embeddings; placement gates on these — a model advertising none cannot be selected)", capability: "string (optional, filter list by one capability)", preferred_workloads: "string[] (optional)", quantization: "string (optional, e.g. Q4_K_M)", enabled: "boolean (optional; filters list)" }, computeTools.sidekick_compute_models, "medium"],
  ["compute_jobs", "Manage allowlisted compute jobs: list, get, create, cancel, retry, recover, view stats and artifacts", { action: "string (list|get|create|cancel|retry|recover|stats|artifacts|reconcile_artifact_custody)", job_id: "string (job ID for get/cancel/retry/artifacts)", job_type: "string (canonical job type for create: chat|generate|embeddings|text_embedding)", capability: "string (optional, requested capability for create, preserved exactly, e.g. openvino.text_embedding)", request_payload: "object (optional, structured executor request payload for create; validated by the job contract and executor rules)", capability_requirements: "object (optional, capability requirements for create, e.g. { executor, model })", data_classification: "string (optional, public|internal|private for create; preserved when supplied)", prompt: "string (optional, create convenience mapped to request_payload.prompt)", model: "string (optional, create convenience mapped to request_payload.model)", provider: "string (optional, create convenience mapped to request_payload.provider)", output_budget: "string (optional, normal|complex|large output tier for chat/generate)", source_job_id: "string (optional, completed source Compute job whose result is injected after claim)", timeout_ms: "number (optional, job timeout ms for create)", max_retries: "number (optional, retries after first attempt for create)", idempotency_key: "string (optional, idempotency key for create)", reason: "string (optional, cancellation/retry reason)", status: "string (optional, filter by status for list)", limit: "number (optional, max results for list)", project: "string (optional, create metadata or list filter)", provider_id: "string (optional, filter by provider for list)", worker_id: "string (optional, filter by worker for list)", confirm: "boolean (optional, execute reconcile_artifact_custody; omitted or false is a dry run)" }, computeTools.sidekick_compute_jobs, "medium"],
  ["compute_route", "Explain routing decisions and manage routing rules for allowlisted compute workloads", { action: "string (explain|list_rules|create_rule|delete_rule)", workload_class: "string (chat|generate|embeddings for explain)", capabilities_required: "string (comma-separated capabilities for explain)", data_classification: "string (public|internal|private for explain)", trust_level: "string (untrusted|community|known|trusted|internal for explain)", rule_id: "string (routing rule ID for delete_rule)", rule_name: "string (rule name for create_rule)", priority: "number (rule priority for create_rule, lower=higher)", description: "string (optional, rule description for create_rule)", preferred_providers: "array (preferred provider IDs for create_rule)", preferred_models: "array (preferred model IDs for create_rule)", fallback_providers: "array (optional, fallback provider IDs for create_rule)", max_latency_ms: "number (optional, max latency requirement for create_rule)" }, computeTools.sidekick_compute_route, "medium"],
];

const descriptors = Object.freeze(definitions.map(([name, description, args, handler, risk]) => Object.freeze({
  name,
  description,
  args,
  schema: TOOL_SCHEMAS[name],
  handler,
  risk,
  category: "Compute",
  source: "builtin",
  family: "compute",
})));

module.exports = { descriptors };
