function createBlackboxQuery({ dbStore, ensureSchema, safeId, parseJson, nowIso, readArtifactByPath, listAnalyses }) {
  const incident = row => row ? ({ id: row.id, title: row.title, description: row.description, project: row.project, environment: row.environment, host: row.host, severity: row.severity, lifecycle_state: row.lifecycle_state, created_at: row.created_at, updated_at: row.updated_at, detected_at: row.detected_at, resolved_at: row.resolved_at, source: row.source, task_id: row.task_id, session_id: row.session_id, correlation_id: row.correlation_id, tags: parseJson(row.tags_json, []), pinned: !!row.pinned, retention_class: row.retention_class, expires_at: row.expires_at, last_accessed_at: row.last_accessed_at, root_cause: row.root_cause, resolution: row.resolution, current_diagnosis_id: row.current_diagnosis_id, redaction_status: row.redaction_status, schema_version: row.schema_version }) : null;
  const capture = row => row ? ({ id: row.id, incident_id: row.incident_id, capture_type: row.capture_type, trigger: row.trigger, requested_sources: parseJson(row.requested_sources_json, []), profile: row.profile, started_at: row.started_at, completed_at: row.completed_at, state: row.state, duration_ms: row.duration_ms, source_count: row.source_count, succeeded_count: row.succeeded_count, failed_count: row.failed_count, timed_out_count: row.timed_out_count, truncated_count: row.truncated_count, total_bytes: row.total_bytes, requested_by: row.requested_by, task_id: row.task_id, session_id: row.session_id, correlation_id: row.correlation_id, cancel_requested: !!row.cancel_requested, error_summary: row.error_summary, capture_version: row.capture_version, diagnostics: parseJson(row.diagnostics_json, {}), retry_of: row.retry_of || null }) : null;
  function source(row, options = {}) { if (!row) return null; const result = { id: row.id, capture_id: row.capture_id, incident_id: row.incident_id, source_key: row.source_key, display_name: row.display_name, category: row.category, collector_type: row.collector_type, command: row.command, arguments_preview: parseJson(row.arguments_preview_json, []), started_at: row.started_at, completed_at: row.completed_at, duration_ms: row.duration_ms, state: row.state, exit_code: row.exit_code, timeout_ms: row.timeout_ms, timed_out: !!row.timed_out, truncated: !!row.truncated, original_byte_count: row.original_byte_count, stored_byte_count: row.stored_byte_count, redaction_count: row.redaction_count, error_category: row.error_category, error_message: row.error_message, content_hash: row.content_hash, normalized: parseJson(row.normalized_json, {}) }; if (options.includeArtifacts) { result.stdout = readArtifactByPath(row.stdout_artifact, options.offset || 0, options.limit || 65536); result.stderr = row.stderr_artifact ? readArtifactByPath(row.stderr_artifact, options.offset || 0, options.limit || 65536) : ""; } return result; }
  function listIncidents(filters = {}) { ensureSchema(); const where = [], params = []; for (const key of ["project", "lifecycle_state", "severity"]) if (filters[key]) { where.push(`${key} = ?`); params.push(filters[key]); } if (filters.search) { where.push("(id LIKE ? OR title LIKE ? OR description LIKE ? OR root_cause LIKE ? OR resolution LIKE ?)"); const q = `%${filters.search}%`; params.push(q, q, q, q, q); } return dbStore.getDb().prepare(`SELECT * FROM blackbox_incidents ${where.length ? "WHERE " + where.join(" AND ") : ""} ORDER BY updated_at DESC LIMIT ? OFFSET ?`).all(...params, Math.min(Number(filters.limit || 50), 200), Number(filters.offset || 0)).map(incident); }
  function listCaptures(id) { ensureSchema(); safeId(id, "incident id"); return dbStore.getDb().prepare("SELECT * FROM blackbox_captures WHERE incident_id = ? ORDER BY started_at DESC").all(id).map(capture); }
  function getIncident(id, options = {}) { ensureSchema(); safeId(id, "incident id"); const db = dbStore.getDb(), result = incident(db.prepare("SELECT * FROM blackbox_incidents WHERE id = ?").get(id)); if (!result) return null; db.prepare("UPDATE blackbox_incidents SET last_accessed_at = ? WHERE id = ?").run(nowIso(), id); if (options.includeCaptures !== false) result.captures = listCaptures(id); if (options.includeTimeline) result.timeline = getTimeline(id); if (options.includeAnalysis && listAnalyses) result.analyses = listAnalyses(id); return result; }
  function getCapture(id, options = {}) { ensureSchema(); safeId(id, "capture id"); const result = capture(dbStore.getDb().prepare("SELECT * FROM blackbox_captures WHERE id = ?").get(id)); if (result && options.includeSources) result.sources = listSources(id); return result; }
  function listSources(id) { ensureSchema(); safeId(id, "capture id"); return dbStore.getDb().prepare("SELECT * FROM blackbox_sources WHERE capture_id = ? ORDER BY started_at ASC").all(id).map(row => source(row)); }
  function getSource(id, options = {}) { ensureSchema(); safeId(id, "source id"); return source(dbStore.getDb().prepare("SELECT * FROM blackbox_sources WHERE id = ?").get(id), { includeArtifacts: true, ...options }); }
  function listObservations(id) { ensureSchema(); safeId(id, "capture id"); return dbStore.getDb().prepare("SELECT * FROM blackbox_observations WHERE capture_id = ? ORDER BY severity DESC, observation_type").all(id).map(row => ({ id: row.id, capture_id: row.capture_id, source_id: row.source_id, observation_type: row.observation_type, subject: row.subject, value: parseJson(row.value_json, null), unit: row.unit, severity: row.severity, observed_at: row.observed_at, validity: row.validity, directness: row.directness, evidence_ref: row.evidence_ref, fingerprint: row.fingerprint })); }
  function getTimeline(id) { ensureSchema(); safeId(id, "incident id"); return dbStore.getDb().prepare("SELECT * FROM blackbox_events WHERE incident_id = ? ORDER BY created_at ASC, id ASC").all(id).map(row => ({ id: row.id, incident_id: row.incident_id, capture_id: row.capture_id, source_id: row.source_id, event_type: row.event_type, actor: row.actor, previous_state: row.previous_state, new_state: row.new_state, reason: row.reason, metadata: parseJson(row.metadata_json, {}), created_at: row.created_at })); }
  return { incidentFromRow: incident, captureFromRow: capture, sourceFromRow: source, listIncidents, getIncident, listCaptures, getCapture, listSources, getSource, listObservations, getTimeline };
}
module.exports = { createBlackboxQuery };
