const fs = require("fs");
const path = require("path");

function createBlackboxStorage({ rootDir, safeId, redact, hashText, nowIso, defaults }) {
  function artifactPath(incidentId, captureId, sourceId, stream) { safeId(incidentId, "incident id"); safeId(captureId, "capture id"); safeId(sourceId, "source id"); safeId(stream, "artifact stream"); return path.join(rootDir, incidentId, captureId, `${sourceId}.${stream}.txt`); }
  function writeArtifact(incidentId, captureId, sourceId, stream, content) { const safeContent = redact(content), finalPath = artifactPath(incidentId, captureId, sourceId, stream), dir = path.dirname(finalPath); fs.mkdirSync(dir, { recursive: true, mode: 0o750 }); const tempPath = `${finalPath}.${process.pid}.${Date.now()}.tmp`; fs.writeFileSync(tempPath, safeContent, { encoding: "utf8", mode: 0o640 }); fs.renameSync(tempPath, finalPath); return { path: finalPath, content, safe_content: safeContent, hash: hashText(safeContent), bytes: Buffer.byteLength(safeContent, "utf8"), redactions: safeContent === String(content || "") ? 0 : 1 }; }
  function readArtifactByPath(filePath, offset = 0, limit = 65536) { if (!filePath) return ""; const resolved = path.resolve(filePath); const root = path.resolve(rootDir); if (!resolved.startsWith(root + path.sep)) throw new Error("Artifact path escaped blackbox directory"); return fs.readFileSync(resolved, "utf8").slice(offset, offset + limit); }
  function getRetentionConfig() { return { defaultClass: process.env.SIDEKICK_BLACKBOX_DEFAULT_RETENTION_CLASS || "standard", classTtls: { transient: Number(process.env.SIDEKICK_BLACKBOX_TTL_TRANSIENT_DAYS || 3), standard: Number(process.env.SIDEKICK_BLACKBOX_TTL_STANDARD_DAYS || 30), important: Number(process.env.SIDEKICK_BLACKBOX_TTL_IMPORTANT_DAYS || 180), archive: Number(process.env.SIDEKICK_BLACKBOX_TTL_ARCHIVE_DAYS || 3650), pinned: null }, dailyCaptureRate: defaults.dailyLimit, maxStoredBytes: defaults.maxBytes, maxIncidentCount: defaults.maxIncidents, purgeGraceDays: Number(process.env.SIDEKICK_BLACKBOX_PURGE_GRACE_DAYS || 1), autoCompress: process.env.SIDEKICK_BLACKBOX_AUTO_COMPRESS === "1" }; }
  function expiresFor(retentionClass, createdAt, pinned, lifecycleState) { if (pinned || lifecycleState === "open" || lifecycleState === "investigating") return null; const cfg = getRetentionConfig(), ttl = cfg.classTtls[retentionClass] === undefined ? cfg.classTtls[cfg.defaultClass] : cfg.classTtls[retentionClass]; if (!ttl) return null; const date = new Date(createdAt || nowIso()); date.setUTCDate(date.getUTCDate() + ttl); return date.toISOString(); }
  return { artifactPath, writeArtifact, readArtifactByPath, getRetentionConfig, expiresFor };
}
module.exports = { createBlackboxStorage };
