"use strict";

/**
 * Deterministic policy for consequential Proxmox operations.
 *
 * These decisions are made by code, never by a language model. A tool handler
 * resolves the concrete facts (which node, which vmid, is it protected, is it
 * Sidekick-owned) and asks this module for a decision; the model only ever
 * chose which named capability to invoke.
 *
 * Two layers combine with Sidekick's own risk/approval system (which gates the
 * whole tool by its risk tier before the handler even runs):
 *
 *   - Protected resources: an administrator can mark guests untouchable by
 *     mutating/destructive operations via pack configuration
 *     (`protected_resources`) — by vmid, tag, or name glob — in addition to
 *     Proxmox's own `protection` flag. A protected match is a hard DENY that no
 *     other policy can override.
 *   - Provenance gating: destructive operations require proven Sidekick
 *     ownership (see lib/provenance.js). This module surfaces that requirement;
 *     the shipped tools never expose a destructive operation, but the decision
 *     shape is the one a future guarded delete will consume.
 *
 * `explain` produces a resolved-facts + decision object for dry-run/preview, so
 * a consequential operation can be described before it is performed.
 */

// Operation -> risk class, purely descriptive metadata used by explain output.
const RISK_CLASS = Object.freeze({
  inspect: "read",
  list: "read",
  status: "read",
  start: "operational",
  shutdown: "operational",
  reboot: "operational",
  clone: "operational",
  create_vm: "mutating",
  create_lxc: "mutating",
  configure: "mutating",
  snapshot_create: "mutating",
  convert_template: "mutating",
  delete: "destructive",
  snapshot_delete: "destructive",
});

function riskClass(operation) {
  return RISK_CLASS[operation] || "mutating";
}

function globToRegExp(glob) {
  const escaped = String(glob).replace(/[.+^${}()|[\]\\]/g, "\\$&").replace(/\*/g, ".*").replace(/\?/g, ".");
  return new RegExp(`^${escaped}$`, "i");
}

/**
 * Resolve whether a target guest is protected. `matchers` is the configured
 * `protected_resources` list; `target` carries the resolved facts.
 * Returns { protected, matched: [reasons] }.
 */
function resolveProtection(matchers, target) {
  const reasons = [];
  if (target && target.proxmox_protection) {
    reasons.push("Proxmox protection flag is set on the guest");
  }
  const list = Array.isArray(matchers) ? matchers : [];
  const tags = Array.isArray(target && target.tags) ? target.tags.map(t => String(t).toLowerCase()) : [];
  for (const m of list) {
    if (!m || typeof m !== "object") continue;
    if (m.vmid !== undefined && Number(m.vmid) === Number(target && target.vmid)) reasons.push(`configured protected vmid ${m.vmid}`);
    if (m.tag !== undefined && tags.includes(String(m.tag).toLowerCase())) reasons.push(`configured protected tag "${m.tag}"`);
    if (m.name !== undefined && target && typeof target.name === "string" && globToRegExp(m.name).test(target.name)) reasons.push(`configured protected name pattern "${m.name}"`);
  }
  return { protected: reasons.length > 0, matched: reasons };
}

/**
 * Build a deterministic explain/dry-run object from resolved facts and a policy
 * decision. This is never generated by a model.
 */
function explain({ operation, profile, target, decision, expected_effect, provenance }) {
  return {
    requested: operation,
    risk_class: riskClass(operation),
    profile: profile || null,
    resolved: {
      node: (target && target.node) || null,
      vmid: (target && target.vmid) != null ? target.vmid : null,
      name: (target && target.name) || null,
      type: (target && target.type) || null,
      proxmox_protection: Boolean(target && target.proxmox_protection),
      sidekick_managed: Boolean(provenance && provenance.managed),
      is_test_resource: Boolean(provenance && provenance.test),
      provenance_marker: (provenance && provenance.provenance && provenance.provenance.marker) || null,
      created_by_run: (provenance && provenance.provenance && provenance.provenance.run) || null,
    },
    expected_effect: expected_effect || null,
    decision: decision || { result: "allowed", reasons: [] },
  };
}

/**
 * Decide a mutating/destructive operation against a resolved target.
 * `requireOwnership` (true for destructive) demands proven Sidekick provenance.
 * Returns { result: "allowed"|"denied", reasons }.
 */
function decide({ matchers, target, provenance, requireOwnership = false, blockIfProtected = true }) {
  const reasons = [];
  const protection = resolveProtection(matchers, target);
  if (blockIfProtected && protection.protected) {
    return { result: "denied", reasons: protection.matched.map(r => `protected: ${r}`) };
  }
  if (requireOwnership && !(provenance && provenance.managed)) {
    return { result: "denied", reasons: ["ownership could not be proven (missing sidekick-managed tag and/or provenance marker)"] };
  }
  if (protection.protected) reasons.push(...protection.matched.map(r => `note: ${r}`));
  return { result: "allowed", reasons };
}

module.exports = { RISK_CLASS, riskClass, resolveProtection, explain, decide };
