"use strict";

/**
 * Resource provenance for Proxmox guests Sidekick creates or manages.
 *
 * The problem this solves: before Sidekick performs a consequential (especially
 * destructive) operation on a guest, it must be able to prove — from explicit,
 * recorded evidence, not from a familiar-looking name — that the guest is one it
 * created and owns. A name is never proof.
 *
 * Two independent markers are written at creation time and both are checked
 * before an ownership-gated operation:
 *
 *   1. A Proxmox TAG (`sidekick-managed`, plus `sidekick-test` for test
 *      resources). Tags are first-class, queryable, and visible in the Proxmox
 *      UI, so an operator can see at a glance what Sidekick owns.
 *   2. A parseable marker block embedded in the guest DESCRIPTION carrying the
 *      pack, the run/correlation id, a unique per-resource marker, and whether
 *      the resource is a disposable test resource.
 *
 * Ownership verification reads the guest's CURRENT config (read-before-act) and
 * requires the marker to be present and, for test cleanup, to match the exact
 * unique marker generated by that test. Anything short of a proven match is a
 * refusal, never a best guess.
 *
 * The Proxmox-side markers are self-contained: verification needs only the guest
 * config, so it works even if Sidekick's own state store is unavailable. An
 * optional `record`/`recall` hook mirrors provenance into a Sidekick state
 * store for cross-referencing, but the Proxmox markers are authoritative for the
 * ownership decision.
 */

const MANAGED_TAG = "sidekick-managed";
const TEST_TAG = "sidekick-test";
const MARKER_OPEN = "[sidekick]";
const MARKER_CLOSE = "[/sidekick]";
// Proxmox tags are lowercased and restricted to [a-z0-9_-]; keep ours in range.
const TAG_RE = /^[a-z0-9][a-z0-9_-]{0,62}$/;

function isoNow() {
  return new Date().toISOString();
}

/** A unique, unmistakable marker id for one created resource. */
function newMarker(prefix = "sk") {
  // Time + randomness; module code (not a workflow script) may use Date/random.
  const rand = Math.random().toString(36).slice(2, 10);
  return `${prefix}-${Date.now().toString(36)}-${rand}`;
}

function normalizeTags(value) {
  if (!value) return [];
  return String(value)
    .split(/[;,\s]+/)
    .map(t => t.trim().toLowerCase())
    .filter(Boolean);
}

function tagsToString(tags) {
  const unique = [...new Set(tags.map(t => t.toLowerCase()).filter(t => TAG_RE.test(t)))];
  return unique.join(";");
}

/**
 * Build the provenance markers (tags + description block) to attach to a new
 * resource. Returns { tags, description, marker } to merge into create params.
 */
// Strip anything that could forge or split the marker block: the delimiter
// tokens themselves and newlines in a field value. Applied to every value that
// enters the block so a caller-supplied description or a framework-supplied run
// id can never inject marker fields.
function sanitizeMarkerText(value) {
  return String(value == null ? "" : value)
    .split(MARKER_OPEN).join("(sidekick)")
    .split(MARKER_CLOSE).join("(/sidekick)");
}
function sanitizeFieldValue(value) {
  return sanitizeMarkerText(value).replace(/[\r\n]+/g, " ").trim();
}

function buildProvenance({ pack = "proxmox", run = null, test = false, marker = null, extraTags = [], baseDescription = "" } = {}) {
  const resolvedMarker = marker || newMarker(test ? "sktest" : "sk");
  const tags = [MANAGED_TAG, ...(test ? [TEST_TAG] : []), ...extraTags];
  const fields = {
    managed: "true",
    pack: sanitizeFieldValue(pack),
    run: sanitizeFieldValue(run || "none"),
    marker: resolvedMarker,
    created: isoNow(),
    test: test ? "true" : "false",
  };
  const block = [MARKER_OPEN, ...Object.entries(fields).map(([k, v]) => `${k}=${v}`), MARKER_CLOSE].join("\n");
  // The caller's free-text description precedes the block but cannot contain the
  // delimiter tokens, so the authoritative block is always the LAST one and
  // cannot be shadowed by a forged block in the description.
  const safeBase = sanitizeMarkerText(baseDescription).trim();
  const description = safeBase ? `${safeBase}\n\n${block}` : block;
  return { tags: tagsToString(tags), description, marker: resolvedMarker, fields };
}

/** Parse the provenance marker block out of a guest description. */
function parseProvenance(description) {
  if (typeof description !== "string") return null;
  // The authoritative block is the LAST one: buildProvenance appends it after
  // sanitizing the caller's text, so a forged block in a caller-supplied
  // description (which cannot itself contain the delimiter tokens) never wins.
  const start = description.lastIndexOf(MARKER_OPEN);
  const end = description.indexOf(MARKER_CLOSE, start);
  if (start === -1 || end === -1 || end < start) return null;
  const body = description.slice(start + MARKER_OPEN.length, end);
  const fields = {};
  for (const line of body.split(/\r?\n/)) {
    const m = line.match(/^\s*([a-z_]+)=(.*)$/i);
    if (m) fields[m[1]] = m[2].trim();
  }
  if (fields.managed !== "true") return null;
  return {
    managed: true,
    pack: fields.pack || null,
    run: fields.run && fields.run !== "none" ? fields.run : null,
    marker: fields.marker || null,
    created: fields.created || null,
    test: fields.test === "true",
  };
}

/**
 * Read a guest's current config and derive its provenance evidence.
 * Returns { tags, provenance, managed, test, protected } with `managed` true
 * only when BOTH the tag and the description marker agree.
 */
function readProvenance(config) {
  const tags = normalizeTags(config && config.tags);
  const provenance = parseProvenance(config && config.description);
  const taggedManaged = tags.includes(MANAGED_TAG);
  const managed = Boolean(provenance && provenance.managed && taggedManaged);
  return {
    tags,
    provenance,
    managed,
    test: Boolean(provenance && provenance.test) && tags.includes(TEST_TAG),
    // Proxmox's own protection flag: when set, the guest cannot be removed.
    protection: config && (config.protection === 1 || config.protection === "1" || config.protection === true),
  };
}

/**
 * Decide whether an ownership-gated operation may proceed against a guest.
 *
 * `requireManaged`  – the guest must carry proven Sidekick provenance.
 * `requireMarker`   – (test cleanup) the guest's marker must equal this exact
 *                      value, so a test can only ever delete the resource it
 *                      itself created.
 * `requireTest`     – the guest must be a disposable test resource.
 *
 * Returns { ok, reason, evidence }.
 */
function checkOwnership(config, { requireManaged = true, requireMarker = null, requireTest = false } = {}) {
  const evidence = readProvenance(config);
  if (evidence.protection) {
    return { ok: false, reason: "The guest has Proxmox protection enabled and cannot be targeted by a destructive operation.", evidence };
  }
  if (requireManaged && !evidence.managed) {
    return { ok: false, reason: "Ownership could not be proven: the guest does not carry both the sidekick-managed tag and a valid provenance marker.", evidence };
  }
  if (requireTest && !evidence.test) {
    return { ok: false, reason: "The guest is not marked as a disposable Sidekick test resource.", evidence };
  }
  if (requireMarker) {
    const actual = evidence.provenance && evidence.provenance.marker;
    if (actual !== requireMarker) {
      return { ok: false, reason: `Provenance marker mismatch: expected ${requireMarker}, found ${actual || "none"}. Refusing to act on a resource this operation did not create.`, evidence };
    }
  }
  return { ok: true, reason: null, evidence };
}

module.exports = {
  MANAGED_TAG,
  TEST_TAG,
  newMarker,
  normalizeTags,
  tagsToString,
  buildProvenance,
  parseProvenance,
  readProvenance,
  checkOwnership,
};
