"use strict";

const crypto = require("crypto");
const dbStore = require("../db");
const { normalizeScope } = require("./network-scope");

const MAX_LIMIT = 100;
function db() { return dbStore.getDb(); }
function now() { return new Date().toISOString(); }
function id(prefix) { return `${prefix}_${crypto.randomBytes(9).toString("hex")}`; }
function ensureSchema() {
  db().exec(`CREATE TABLE IF NOT EXISTS platform_network_scopes (scope_id TEXT PRIMARY KEY, name TEXT UNIQUE NOT NULL, state TEXT NOT NULL DEFAULT 'active', current_revision INTEGER NOT NULL, created_by TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, disabled_at TEXT, metadata_json TEXT NOT NULL DEFAULT '{}'); CREATE TABLE IF NOT EXISTS platform_network_scope_revisions (scope_id TEXT NOT NULL, revision INTEGER NOT NULL, digest TEXT NOT NULL, policy_json TEXT NOT NULL, created_by TEXT NOT NULL, created_at TEXT NOT NULL, expires_at TEXT, PRIMARY KEY(scope_id, revision), FOREIGN KEY(scope_id) REFERENCES platform_network_scopes(scope_id)); CREATE UNIQUE INDEX IF NOT EXISTS idx_network_scope_digest ON platform_network_scope_revisions(digest);`);
}
function safe(row, policy, revision = row.current_revision) { return row ? { ...policy, scope_id: row.scope_id, name: row.name, state: row.state, revision, current_revision: row.current_revision, is_current: revision === row.current_revision, digest: policy.digest, created_by: row.created_by, created_at: row.created_at, updated_at: row.updated_at, disabled_at: row.disabled_at || null, enabled: row.state === "active" } : null; }
function get(scopeRef, revision) { ensureSchema(); const ref = String(scopeRef || "").trim(); if (!ref) return null; const scope = db().prepare("SELECT * FROM platform_network_scopes WHERE scope_id = ? OR name = ?").get(ref, ref); if (!scope) return null; const rev = revision == null ? scope.current_revision : Number(revision); const row = db().prepare("SELECT * FROM platform_network_scope_revisions WHERE scope_id = ? AND revision = ?").get(scope.scope_id, rev); if (!row) return null; const policy = JSON.parse(row.policy_json); return safe(scope, { ...policy, scope_id: scope.scope_id, name: scope.name, revision: row.revision, digest: row.digest, enabled: scope.state === "active" }, rev); }
function event(type, actor, scope, payload = {}) { try { require("../platform/kernel").appendEvent({ event_type: type, source: "network-scope", actor_id: actor, subject_type: "network_scope", subject_id: scope.scope_id, payload: { scope_id: scope.scope_id, revision: scope.revision, digest: scope.digest, ...payload }, correlation_id: scope.scope_id }); } catch {} }
function requireActor(actor) { const value = String(actor || "").trim(); if (!value || value.length > 200) throw new Error("operator actor is required"); return value; }
function create(input, actor) { ensureSchema(); actor = requireActor(actor); const policy = normalizeScope(input); const name = policy.name; if (db().prepare("SELECT 1 FROM platform_network_scopes WHERE name = ?").get(name)) throw new Error("network scope name already exists"); const scopeId = id("nscope"), ts = now(), state = policy.enabled ? "active" : "disabled"; db().transaction(() => { db().prepare("INSERT INTO platform_network_scopes (scope_id,name,state,current_revision,created_by,created_at,updated_at,metadata_json) VALUES (?,?, ?,1,?,?,?,?)").run(scopeId, name, state, actor, ts, ts, JSON.stringify(input.metadata || {})); db().prepare("INSERT INTO platform_network_scope_revisions (scope_id,revision,digest,policy_json,created_by,created_at,expires_at) VALUES (?,?,?,?,?,?,?)").run(scopeId, 1, policy.digest, JSON.stringify(policy), actor, ts, policy.expires_at); })(); const result = get(scopeId); event("network_scope.created", actor, result); return result; }
function update(scopeRef, input, actor) { actor = requireActor(actor); const current = get(scopeRef); if (!current) throw new Error("network scope not found"); const policy = normalizeScope({ ...input, name: current.name }); const revision = current.revision + 1, ts = now(); db().transaction(() => { db().prepare("INSERT INTO platform_network_scope_revisions (scope_id,revision,digest,policy_json,created_by,created_at,expires_at) VALUES (?,?,?,?,?,?,?)").run(current.scope_id, revision, policy.digest, JSON.stringify(policy), actor, ts, policy.expires_at); db().prepare("UPDATE platform_network_scopes SET current_revision=?,updated_at=? WHERE scope_id=?").run(revision, ts, current.scope_id); })(); const result = get(current.scope_id); event("network_scope.revised", actor, result, { previous_revision: current.revision }); return result; }
function list(query = {}) { ensureSchema(); const limit = Math.max(1, Math.min(Number(query.limit) || 50, MAX_LIMIT)); const rows = db().prepare("SELECT * FROM platform_network_scopes WHERE (? IS NULL OR state = ?) ORDER BY name LIMIT ?").all(query.state || null, query.state || null, limit); return rows.map(row => get(row.scope_id)); }
function setState(scopeRef, state, actor) { actor = requireActor(actor); const current = get(scopeRef); if (!current) throw new Error("network scope not found"); if (!["active", "disabled", "deleted"].includes(state)) throw new Error("invalid network scope state"); if (state === "deleted" && db().prepare("SELECT 1 FROM platform_research_campaigns WHERE json_extract(metadata_json,'$.network_scope.scope_id') = ? LIMIT 1").get(current.scope_id)) throw new Error("network scope has durable research references; disable it instead"); const ts = now(); db().prepare("UPDATE platform_network_scopes SET state=?,updated_at=?,disabled_at=? WHERE scope_id=?").run(state, ts, state === "active" ? null : ts, current.scope_id); const result = get(current.scope_id); event(`network_scope.${state}`, actor, result); return result; }
function validate(input) { return normalizeScope(input); }
function references(scopeId) { ensureSchema(); const rows = db().prepare("SELECT campaign_id, project_id, state FROM platform_research_campaigns WHERE json_extract(metadata_json,'$.network_scope.scope_id') = ? LIMIT 100").all(scopeId); return rows; }

module.exports = { ensureSchema, create, update, get, list, setState, validate, references };
