function createConnectorStore({ ensureSchema, dbStore, states, transitions, json, parseJson, nowIso, newId, appendEvent }) {
  function normalize(row) { return row ? { ...row, capabilities: parseJson(row.capabilities_json, []), config: parseJson(row.config_json, {}), health: parseJson(row.health_json, {}), metadata: parseJson(row.metadata_json, {}) } : null; }
  function secretRef(value) { if (value === undefined || value === null || value === "") return null; const ref = String(value); if (!/^secret:[A-Za-z0-9_.:/-]{1,190}$/.test(ref)) throw new Error("secret_ref must be an opaque secret:name reference"); return ref; }
  function endpoint(value) { if (value === undefined || value === null || value === "") return null; let parsed; try { parsed = new URL(String(value)); } catch { throw new Error("connector endpoint must be a valid URL"); } if (!["http:", "https:"].includes(parsed.protocol) || parsed.username || parsed.password) throw new Error("connector endpoint must be http(s) without embedded credentials"); return parsed.toString(); }
  function connectorEndpoint(type, value) { const normalized = endpoint(value); if (normalized && String(type).toLowerCase() === "github" && !normalized.startsWith("https://")) throw new Error("github connector endpoint must use HTTPS"); return normalized; }
  function safeConfig(value, pathName = "config") { if (!value || typeof value !== "object") return; for (const [key, child] of Object.entries(value)) { if (/(api[_-]?key|access[_-]?token|password|private[_-]?key|webhook[_-]?url|^secret$)/i.test(key) && !/_ref$/i.test(key)) throw new Error(`${pathName}.${key} must use a secret reference, not a credential value`); if (child && typeof child === "object") safeConfig(child, `${pathName}.${key}`); } }
  function getConnector(id) { ensureSchema(); return normalize(dbStore.getDb().prepare("SELECT * FROM platform_connectors WHERE connector_id = ?").get(String(id))); }
  function registerConnector(input = {}) { ensureSchema(); const name = String(input.name || "").trim(), type = String(input.type || "").trim(); if (!name) throw new Error("connector name is required"); if (!type) throw new Error("connector type is required"); const config = input.config || {}; safeConfig(config); const id = input.connector_id || newId("connector"), ts = nowIso(); dbStore.getDb().prepare("INSERT INTO platform_connectors (connector_id, name, type, state, endpoint, secret_ref, capabilities_json, config_json, registered_at, updated_at, metadata_json) VALUES (?, ?, ?, 'registered', ?, ?, ?, ?, ?, ?, ?)").run(id, name, type, connectorEndpoint(type, input.endpoint), secretRef(input.secret_ref), json(input.capabilities || []), json(config), ts, ts, json(input.metadata || {})); const connector = getConnector(id); appendEvent({ event_type: "connector.registered", source: input.source || "platform", subject_type: "connector", subject_id: id, payload: { name, type, secret_ref: input.secret_ref ? "present" : null }, correlation_id: id }); return connector; }
  function listConnectors({ state, type, limit = 50 } = {}) { ensureSchema(); const conditions = [], params = []; if (state) { if (!states.includes(state)) throw new Error(`Invalid connector state: ${state}`); conditions.push("state = ?"); params.push(state); } if (type) { conditions.push("type = ?"); params.push(String(type)); } const bounded = Math.max(1, Math.min(Number(limit) || 50, 100)); return dbStore.getDb().prepare(`SELECT * FROM platform_connectors ${conditions.length ? `WHERE ${conditions.join(" AND ")}` : ""} ORDER BY updated_at DESC LIMIT ?`).all(...params, bounded).map(normalize); }
  function listConnectorEvents(id, limit = 20) { ensureSchema(); const bounded = Math.max(1, Math.min(Number(limit) || 20, 100)); return dbStore.getDb().prepare("SELECT event_id, event_type, timestamp, severity, payload_json FROM platform_execution_events WHERE subject_type = 'connector' AND subject_id = ? ORDER BY rowid DESC LIMIT ?").all(String(id), bounded).map(row => ({ event_id: row.event_id, event_type: row.event_type, timestamp: row.timestamp, severity: row.severity, payload: parseJson(row.payload_json, {}) })); }
  function transitionConnector(id, next, details = {}) { ensureSchema(); if (!states.includes(next)) throw new Error(`Invalid connector state: ${next}`); const current = getConnector(id); if (!current) throw new Error(`Connector not found: ${id}`); if (!(transitions[current.state] || []).includes(next)) throw new Error(`Invalid connector transition: ${current.state} -> ${next}`); dbStore.getDb().prepare("UPDATE platform_connectors SET state = ?, error = ?, updated_at = ? WHERE connector_id = ?").run(next, next === "error" ? String(details.error || "connector error").slice(0, 500) : null, nowIso(), current.connector_id); appendEvent({ event_type: "connector.state_changed", source: details.source || "platform", subject_type: "connector", subject_id: current.connector_id, severity: next === "error" ? "warning" : "info", payload: { name: current.name, from: current.state, to: next, error: next === "error" ? String(details.error || "connector error").slice(0, 500) : null }, correlation_id: current.connector_id }); return getConnector(current.connector_id); }
  return { normalize, secretRef, endpoint, safeConfig, registerConnector, getConnector, listConnectors, listConnectorEvents, transitionConnector };
}
module.exports = { createConnectorStore };
