const TOOL_RISK = {
  bash: "critical",
  write: "critical",
  db_restore: "critical",
  runbook: "critical",
  ops: "critical",
  mission: "critical",
  sandbox: "critical",
  evolve: "critical",
  process: "high",
  service: "high",
  cron: "high",
  delay: "high",
  watch: "high",
  github: "high",
  ci_status: "low",
  teach: "high",
  secret: "high",
  security_scan: "low",
  db_migrate: "high",
  queue: "high",
  orchestrate: "high",
  notify: "medium",
  read: "medium",
  archive: "medium",
  git: "medium",
  web_fetch: "medium",
  llm: "medium",
  context: "medium",
  session: "medium",
  handoff: "medium",
  memory: "medium",
  memory_export: "low",
  memory_import: "medium",
  memory_manage: "medium",
  sync_identity: "low",
  sync_export: "low",
  sync_import: "medium",
  sync_diff: "low",
  health: "high",
  snapshot: "medium",
  retry: "medium",
  fresheyes: "medium",
  batch: "medium",
  tail: "medium",
  find: "medium",
  status: "medium",
  extract: "medium",
  changelog: "medium",
  netdiag: "high",
  timeline: "medium",
  circuit: "medium",
  baseline: "high",
  depend: "medium",
  black_box: "medium",
  db_query: "medium",
  db_backup: "medium",
  db_export: "medium",
  redis: "medium",
  ocr: "medium",
  media: "medium",
  transcribe: "medium",
  analytics: "medium",
  insight_report: "low",
  embed: "low",
  ollama: "low",
  tunnel: "high",
  download: "medium",
  wireguard: "high",
  nginx: "high",
  tools: "low",
  knowledge: "low",
  compute: "medium",
  compute_nodes: "medium",
  compute_providers: "medium",
  compute_models: "low",
  compute_jobs: "medium",
  compute_route: "medium",
  delete: "low",
  resume: "low",
  metrics: "low",
};

const TOOL_CATEGORIES = {
  'bash': 'Core',
  'tools': 'Core',
  'read': 'Core',
  'write': 'Core',
  'list': 'Core',
  'search': 'Core',
  'web_fetch': 'Core',
  'llm': 'Core',
  'respond': 'Core',
  'store': 'Storage',
  'get': 'Storage',
  'delete': 'Storage',
  'resume': 'Storage',
  'list_projects': 'Storage',
  'get_by_project': 'Storage',
  'redis': 'Storage',
  'db_schema': 'Database',
  'db_query': 'Database',
  'db_stats': 'Database',
  'db_backup': 'Database',
  'db_restore': 'Database',
  'db_export': 'Database',
  'db_search': 'Database',
  'db_migrate': 'Database',
  'db_diff': 'Database',
  'analytics': 'Database',
  'insight_report': 'Data Pipeline',
  'git': 'Git & GitHub',
  'github': 'Git & GitHub',
  'ci_status': 'Git & GitHub',
  'process': 'Services',
  'service': 'Services',
  'cron': 'Scheduling',
  'delay': 'Scheduling',
  'notify': 'Communication',
  'webhook': 'Communication',
  'context': 'Context & Learning',
  'session': 'Context & Learning',
  'handoff': 'Context & Learning',
  'memory': 'Context & Learning',
  'teach': 'Context & Learning',
  'embed': 'Context & Learning',
  'ollama': 'Context & Learning',
  'memory_export': 'Context & Learning',
  'memory_import': 'Context & Learning',
  'memory_manage': 'Context & Learning',
  'sync_identity': 'Context & Learning',
  'sync_export': 'Context & Learning',
  'sync_import': 'Context & Learning',
  'sync_diff': 'Context & Learning',
  'transform': 'Data Pipeline',
  'parse': 'Data Pipeline',
  'diff': 'Data Pipeline',
  'hash': 'Data Pipeline',
  'validate': 'Data Pipeline',
  'template': 'Data Pipeline',
  'extract': 'Data Pipeline',
  'anonymize': 'Data Pipeline',
  'diff_files': 'Data Pipeline',
  'health': 'Monitoring',
  'status': 'Monitoring',
  'watch': 'Monitoring',
  'baseline': 'Monitoring',
  'snapshot': 'Monitoring',
  'timeline': 'Monitoring',
  'black_box': 'Monitoring',
  'netdiag': 'Monitoring',
  'queue': 'Workflow',
  'retry': 'Workflow',
  'orchestrate': 'Workflow',
  'runbook': 'Workflow',
  'ops': 'Workflow',
  'mission': 'Workflow',
  'evolve': 'Meta',
  'predict': 'Meta',
  'debug_tool': 'Meta',
  'fresheyes': 'Meta',
  'batch': 'Efficiency',
  'cache': 'Efficiency',
  'summarize': 'Efficiency',
  'filter': 'Efficiency',
  'project': 'Efficiency',
  'tail': 'Efficiency',
  'find': 'Efficiency',
  'secret': 'Security',
  'security_scan': 'Security',
  'sandbox': 'Security',
  'tunnel': 'Networking',
  'wireguard': 'Networking',
  'nginx': 'Networking',
  'changelog': 'Development',
  'depend': 'Development',
  'circuit': 'Reliability',
  'archive': 'Archive',
  'ocr': 'Media',
  'media': 'Media',
  'transcribe': 'Media',
  'download': 'Media',
  'knowledge': 'Context & Learning',
  'metrics': 'Monitoring',
  'compute': 'Compute',
  'compute_nodes': 'Compute',
  'compute_providers': 'Compute',
  'compute_models': 'Compute',
  'compute_jobs': 'Compute',
  'compute_route': 'Compute',
};

const RISK_LEVELS = ["low", "medium", "high", "critical"];

function normalizeToolName(name) {
  return String(name || "").replace(/^sidekick_/, "");
}

function getStaticToolRisk(name) {
  return TOOL_RISK[normalizeToolName(name)] || "low";
}

function getStaticToolCategory(name) {
  return TOOL_CATEGORIES[normalizeToolName(name)] || "Uncategorized";
}

module.exports = {
  TOOL_RISK,
  TOOL_CATEGORIES,
  RISK_LEVELS,
  getStaticToolRisk,
  getStaticToolCategory,
};
